"""

Revision ID: 062fff1a9e86
Revises: 4145b9edb1bc
Create Date: 2022-11-27 17:58:46.587323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '062fff1a9e86'
down_revision = '4145b9edb1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tinh_thanh',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.SMALLINT(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lk_vai_tro_nhan_vien',
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('vai_tro_id', 'user_id')
    )
    op.create_table('quan_huyen',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tuoi', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.BigInteger(), nullable=True),
    sa.Column('height', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.BigInteger(), nullable=True),
    sa.Column('ap_hi', sa.BigInteger(), nullable=True),
    sa.Column('ap_lo', sa.BigInteger(), nullable=True),
    sa.Column('chol', sa.BigInteger(), nullable=True),
    sa.Column('gluc', sa.BigInteger(), nullable=True),
    sa.Column('smoke', sa.BigInteger(), nullable=True),
    sa.Column('alco', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tin_tuc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('ref_name', sa.String(), nullable=True),
    sa.Column('ref_logo', sa.String(), nullable=True),
    sa.Column('ref_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('accepted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xa_phuong',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('quanhuyen_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quanhuyen_id'], ['quan_huyen.id'], ),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'tai_khoan', ['tai_khoan'])
    op.create_foreign_key(None, 'tai_khoan', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'users', 'quan_huyen', ['quan_huyen_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'xa_phuong', ['xa_phuong_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tinh_thanh', ['tinh_thanh_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tinh_thanh', ['tinh_thanh_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'xa_phuong', ['xa_phuong_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'quan_huyen', ['quan_huyen_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tai_khoan', ['tai_khoan_id'], ['id'])
    op.create_foreign_key(None, 'users', 'vai_tro', ['vai_tro_id'], ['id'])
    op.alter_column('vai_tro', 'ten',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_unique_constraint(None, 'vai_tro', ['ten'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vai_tro', type_='unique')
    op.alter_column('vai_tro', 'ten',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tai_khoan', type_='foreignkey')
    op.drop_constraint(None, 'tai_khoan', type_='unique')
    op.drop_table('xa_phuong')
    op.drop_table('tin_tuc')
    op.drop_table('records')
    op.drop_table('quan_huyen')
    op.drop_table('lk_vai_tro_nhan_vien')
    op.drop_table('tinh_thanh')
    # ### end Alembic commands ###
