"""update table user

Revision ID: 0dd78697ac14
Revises: a74f88975347
Create Date: 2022-10-22 17:18:08.354642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd78697ac14'
down_revision = 'a74f88975347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.BigInteger(), nullable=True))
    op.drop_column('users', 'delete_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete_at', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
