"""update table vaitro

Revision ID: 1fb1e9231595
Revises: 0dd78697ac14
Create Date: 2022-10-22 17:22:34.363616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb1e9231595'
down_revision = '0dd78697ac14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vai_tro', sa.Column('deleted_at', sa.BigInteger(), nullable=True))
    op.drop_column('vai_tro', 'delete_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vai_tro', sa.Column('delete_at', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('vai_tro', 'deleted_at')
    # ### end Alembic commands ###
