"""update all table

Revision ID: 2077737cca06
Revises: 0e48c81ebd17
Create Date: 2022-11-04 11:45:00.128302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2077737cca06'
down_revision = '0e48c81ebd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'records', 'users', ['user_id'], ['id'])
    op.add_column('tai_khoan', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'tai_khoan', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tai_khoan', type_='foreignkey')
    op.drop_column('tai_khoan', 'user_id')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'user_id')
    # ### end Alembic commands ###
