"""add table records

Revision ID: 2588d648552b
Revises: 9ac7b417a61d
Create Date: 2022-10-29 17:10:55.114650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2588d648552b'
down_revision = '9ac7b417a61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tuoi', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.BigInteger(), nullable=True),
    sa.Column('height', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.BigInteger(), nullable=True),
    sa.Column('ap_hi', sa.BigInteger(), nullable=True),
    sa.Column('ap_lo', sa.BigInteger(), nullable=True),
    sa.Column('chol', sa.BigInteger(), nullable=True),
    sa.Column('gluc', sa.BigInteger(), nullable=True),
    sa.Column('smoke', sa.BigInteger(), nullable=True),
    sa.Column('alco', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
