"""update table tin_tuc

Revision ID: 268b36602ce4
Revises: c8c939fd858f
Create Date: 2022-11-21 23:16:55.536495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268b36602ce4'
down_revision = 'c8c939fd858f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tin_tuc', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tin_tuc', 'thumbnail')
    # ### end Alembic commands ###
