"""init db

Revision ID: 2a13e7fbc087
Revises: c9385a70dbba
Create Date: 2022-05-04 13:24:27.510410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a13e7fbc087'
down_revision = 'c9385a70dbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tai_khoan', sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tai_khoan', 'last_login_at')
    # ### end Alembic commands ###
