"""update location fields

Revision ID: 312a5ac2eb46
Revises: a014195881c8
Create Date: 2022-11-20 04:26:36.530067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '312a5ac2eb46'
down_revision = 'a014195881c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xa_phuong',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('quanhuyen_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quanhuyen_id'], ['quan_huyen.id'], ),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tinh_thanh', 'quocgia_id')
    op.add_column('users', sa.Column('tinh_thanh_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('quan_huyen_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('xa_phuong_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('so_nha_hien_nay', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tinh_thanh_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('quan_huyen_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('xa_phuong_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('so_nha_thuong_tru', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'xa_phuong', ['xa_phuong_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tinh_thanh', ['tinh_thanh_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'quan_huyen', ['quan_huyen_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'xa_phuong', ['xa_phuong_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'quan_huyen', ['quan_huyen_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tinh_thanh', ['tinh_thanh_hien_nay_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'so_nha_thuong_tru')
    op.drop_column('users', 'xa_phuong_thuong_tru_id')
    op.drop_column('users', 'quan_huyen_thuong_tru_id')
    op.drop_column('users', 'tinh_thanh_thuong_tru_id')
    op.drop_column('users', 'so_nha_hien_nay')
    op.drop_column('users', 'xa_phuong_hien_nay_id')
    op.drop_column('users', 'quan_huyen_hien_nay_id')
    op.drop_column('users', 'tinh_thanh_hien_nay_id')
    op.add_column('tinh_thanh', sa.Column('quocgia_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('xa_phuong')
    # ### end Alembic commands ###
