"""

Revision ID: 4145b9edb1bc
Revises: 64293ec66772
Create Date: 2022-11-27 17:56:12.809816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4145b9edb1bc'
down_revision = '64293ec66772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tinh_thanh',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.SMALLINT(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lk_vai_tro_nhan_vien',
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('vai_tro_id', 'user_id')
    )
    op.create_table('quan_huyen',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tuoi', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.BigInteger(), nullable=True),
    sa.Column('height', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.BigInteger(), nullable=True),
    sa.Column('ap_hi', sa.BigInteger(), nullable=True),
    sa.Column('ap_lo', sa.BigInteger(), nullable=True),
    sa.Column('chol', sa.BigInteger(), nullable=True),
    sa.Column('gluc', sa.BigInteger(), nullable=True),
    sa.Column('smoke', sa.BigInteger(), nullable=True),
    sa.Column('alco', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tin_tuc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('ref_name', sa.String(), nullable=True),
    sa.Column('ref_logo', sa.String(), nullable=True),
    sa.Column('ref_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('accepted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xa_phuong',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('quanhuyen_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quanhuyen_id'], ['quan_huyen.id'], ),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tai_khoan', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('tai_khoan', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('tai_khoan', sa.Column('tai_khoan', sa.String(), nullable=False))
    op.add_column('tai_khoan', sa.Column('mat_khau', sa.String(), nullable=False))
    op.add_column('tai_khoan', sa.Column('dien_thoai', sa.String(length=12), nullable=True))
    op.add_column('tai_khoan', sa.Column('type', sa.SmallInteger(), nullable=True))
    op.add_column('tai_khoan', sa.Column('last_login_at', sa.BigInteger(), nullable=True))
    op.add_column('tai_khoan', sa.Column('created_at', sa.BigInteger(), nullable=True))
    op.add_column('tai_khoan', sa.Column('updated_at', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'tai_khoan', ['tai_khoan'])
    op.create_foreign_key(None, 'tai_khoan', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('deactive_at', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('users', sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('ho', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('ten', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('ho_ten', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('ten_khong_dau', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ngay_sinh', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('dien_thoai', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('ma_cong_dan', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('ngay_cap', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('noi_cap', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('tinh_thanh_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('quan_huyen_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('xa_phuong_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('so_nha_hien_nay', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tinh_thanh_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('quan_huyen_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('xa_phuong_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('so_nha_thuong_tru', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tuoi', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('gioi_tinh', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('height', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('chol', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('gluc', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('smoke', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('alco', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('active', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'users', 'xa_phuong', ['xa_phuong_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'vai_tro', ['vai_tro_id'], ['id'])
    op.create_foreign_key(None, 'users', 'quan_huyen', ['quan_huyen_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tinh_thanh', ['tinh_thanh_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tai_khoan', ['tai_khoan_id'], ['id'])
    op.create_foreign_key(None, 'users', 'quan_huyen', ['quan_huyen_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'xa_phuong', ['xa_phuong_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tinh_thanh', ['tinh_thanh_hien_nay_id'], ['id'])
    op.add_column('vai_tro', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('vai_tro', sa.Column('ten', sa.String(length=80), nullable=False))
    op.add_column('vai_tro', sa.Column('ten_en', sa.String(), nullable=True))
    op.add_column('vai_tro', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('vai_tro', sa.Column('created_at', sa.BigInteger(), nullable=True))
    op.add_column('vai_tro', sa.Column('updated_at', sa.BigInteger(), nullable=True))
    op.add_column('vai_tro', sa.Column('deleted_at', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'vai_tro', ['ten'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vai_tro', type_='unique')
    op.drop_column('vai_tro', 'deleted_at')
    op.drop_column('vai_tro', 'updated_at')
    op.drop_column('vai_tro', 'created_at')
    op.drop_column('vai_tro', 'created_by')
    op.drop_column('vai_tro', 'ten_en')
    op.drop_column('vai_tro', 'ten')
    op.drop_column('vai_tro', 'id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'status')
    op.drop_column('users', 'password')
    op.drop_column('users', 'active')
    op.drop_column('users', 'alco')
    op.drop_column('users', 'smoke')
    op.drop_column('users', 'gluc')
    op.drop_column('users', 'chol')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'gioi_tinh')
    op.drop_column('users', 'tuoi')
    op.drop_column('users', 'so_nha_thuong_tru')
    op.drop_column('users', 'xa_phuong_thuong_tru_id')
    op.drop_column('users', 'quan_huyen_thuong_tru_id')
    op.drop_column('users', 'tinh_thanh_thuong_tru_id')
    op.drop_column('users', 'so_nha_hien_nay')
    op.drop_column('users', 'xa_phuong_hien_nay_id')
    op.drop_column('users', 'quan_huyen_hien_nay_id')
    op.drop_column('users', 'tinh_thanh_hien_nay_id')
    op.drop_column('users', 'email')
    op.drop_column('users', 'noi_cap')
    op.drop_column('users', 'ngay_cap')
    op.drop_column('users', 'ma_cong_dan')
    op.drop_column('users', 'dien_thoai')
    op.drop_column('users', 'ngay_sinh')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'ten_khong_dau')
    op.drop_column('users', 'ho_ten')
    op.drop_column('users', 'ten')
    op.drop_column('users', 'ho')
    op.drop_column('users', 'vai_tro_id')
    op.drop_column('users', 'tai_khoan_id')
    op.drop_column('users', 'id')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'deactive_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'tai_khoan', type_='foreignkey')
    op.drop_constraint(None, 'tai_khoan', type_='unique')
    op.drop_column('tai_khoan', 'updated_at')
    op.drop_column('tai_khoan', 'created_at')
    op.drop_column('tai_khoan', 'last_login_at')
    op.drop_column('tai_khoan', 'type')
    op.drop_column('tai_khoan', 'dien_thoai')
    op.drop_column('tai_khoan', 'mat_khau')
    op.drop_column('tai_khoan', 'tai_khoan')
    op.drop_column('tai_khoan', 'user_id')
    op.drop_column('tai_khoan', 'id')
    op.drop_table('xa_phuong')
    op.drop_table('tin_tuc')
    op.drop_table('records')
    op.drop_table('quan_huyen')
    op.drop_table('lk_vai_tro_nhan_vien')
    op.drop_table('tinh_thanh')
    # ### end Alembic commands ###
