"""udapte table tin_tuc

Revision ID: 445ab4f003e5
Revises: 529d31394b82
Create Date: 2022-11-20 06:29:35.532686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445ab4f003e5'
down_revision = '529d31394b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tin_tuc', sa.Column('ref_name', sa.String(), nullable=True))
    op.add_column('tin_tuc', sa.Column('ref_logo', sa.String(), nullable=True))
    op.add_column('tin_tuc', sa.Column('ref_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tin_tuc', 'ref_link')
    op.drop_column('tin_tuc', 'ref_logo')
    op.drop_column('tin_tuc', 'ref_name')
    # ### end Alembic commands ###
