"""update model

Revision ID: 5577d25a8728
Revises: 
Create Date: 2022-04-29 15:55:25.468986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5577d25a8728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ho_so_nang_luc_don_vi')
    op.drop_table('thong_tin_don_vi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thong_tin_don_vi',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('tong_so_giuong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_benh_nhan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_dang_dieu_tri', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_cong_don', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_nhap_moi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_chuyen_tang_tren', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_chuyen_tang_duoi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chi_tieu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_ecmo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_loc_mau', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_may_tho_hfnc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_may_tho_cpap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_may_tho_bipap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_giuong_tho_oxy_thuong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_giuong_co_oxy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ecmo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc_mau', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_hfnc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_cpap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_bipap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_giuong_tho_oxy_thuong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_giuong_co_oxy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='thong_tin_don_vi_pkey')
    )
    op.create_table('ho_so_nang_luc_don_vi',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('don_vi_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('ten_don_vi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tong_so_giuong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_benh_nhan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_dang_dieu_tri', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_cong_don', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('khong_benh_nen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ko_benh_nen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_nhap_moi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_chuyen_tang_tren', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_chuyen_tang_duoi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_tong_nvy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_benh_nhan_khong_mac_covid_19_tu_vong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_du_kien_xet_nghiem_ngay_hom_sau', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ecmo_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ecmo_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc_mau_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc_mau_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_xam_lan_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_xam_lan_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_hfnc_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_hfnc_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_cpap_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_cpap_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_bipap_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_bipap_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_giuong_tho_oxy_thuong_gong_kinh_mat_na_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_giuong_tho_oxy_thuong_gong_kinh_mat_na_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tang', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at_view', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_tong_nvy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_co_oxy_tho_oxy_thuong_tho_may_tho_hfnc_cpap_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_co_oxy_tho_oxy_thuong_tho_may_tho_hfnc_cpap_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ca_mac_tang_1_luy_ke', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ca_mac_tang_1_hom_nay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('khoi_benh_tang_1_luy_ke', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('khoi_benh_tang_1_hom_nay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('giuong_benh_tang_1_luy_ke', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('giuong_benh_tang_1_hom_nay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['don_vi_id'], ['don_vi.id'], name='ho_so_nang_luc_don_vi_don_vi_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ho_so_nang_luc_don_vi_pkey')
    )
    # ### end Alembic commands ###
