"""update all table

Revision ID: 5e8f70431b8f
Revises: 2077737cca06
Create Date: 2022-11-06 14:08:00.113116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e8f70431b8f'
down_revision = '2077737cca06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deactive_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ho', sa.String(length=80), nullable=True),
    sa.Column('ten', sa.String(length=80), nullable=True),
    sa.Column('ho_ten', sa.String(length=80), nullable=True),
    sa.Column('ten_khong_dau', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('ngay_sinh', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.String(), nullable=True),
    sa.Column('dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('ma_cong_dan', sa.String(length=80), nullable=True),
    sa.Column('ngay_cap', sa.BigInteger(), nullable=True),
    sa.Column('noi_cap', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('so_nha', sa.String(), nullable=True),
    sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'lk_vai_tro_nhan_vien', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'records', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tai_khoan', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tai_khoan', type_='foreignkey')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_constraint(None, 'lk_vai_tro_nhan_vien', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
