"""update table users

Revision ID: 6ea272fd5983
Revises: 310bc1eca8c1
Create Date: 2022-10-22 17:37:33.725771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ea272fd5983'
down_revision = '310bc1eca8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ids', postgresql.UUID(as_uuid=True), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'ids')
    # ### end Alembic commands ###
