"""update table user

Revision ID: 80004b05942a
Revises: ee379b167a88
Create Date: 2022-11-14 00:57:54.600523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80004b05942a'
down_revision = 'ee379b167a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
