"""

Revision ID: 999336008f29
Revises: 2b69edfe3018
Create Date: 2022-11-27 17:39:09.548403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999336008f29'
down_revision = '2b69edfe3018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lk_vai_tro_nhan_vien', 'vai_tro', ['vai_tro_id'], ['id'])
    op.create_foreign_key(None, 'lk_vai_tro_nhan_vien', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'quan_huyen', 'tinh_thanh', ['tinhthanh_id'], ['id'])
    op.create_foreign_key(None, 'records', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'tai_khoan', ['tai_khoan'])
    op.create_foreign_key(None, 'tai_khoan', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tin_tuc', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tin_tuc', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tin_tuc', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'tin_tuc', 'users', ['accepted_by'], ['id'])
    op.create_foreign_key(None, 'users', 'quan_huyen', ['quan_huyen_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tai_khoan', ['tai_khoan_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tinh_thanh', ['tinh_thanh_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'xa_phuong', ['xa_phuong_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'users', 'vai_tro', ['vai_tro_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tinh_thanh', ['tinh_thanh_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'xa_phuong', ['xa_phuong_thuong_tru_id'], ['id'])
    op.create_foreign_key(None, 'users', 'quan_huyen', ['quan_huyen_thuong_tru_id'], ['id'])
    op.alter_column('vai_tro', 'ten',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_unique_constraint(None, 'vai_tro', ['ten'])
    op.create_foreign_key(None, 'xa_phuong', 'quan_huyen', ['quanhuyen_id'], ['id'])
    op.create_foreign_key(None, 'xa_phuong', 'tinh_thanh', ['tinhthanh_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xa_phuong', type_='foreignkey')
    op.drop_constraint(None, 'xa_phuong', type_='foreignkey')
    op.drop_constraint(None, 'vai_tro', type_='unique')
    op.alter_column('vai_tro', 'ten',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    op.drop_constraint(None, 'tai_khoan', type_='foreignkey')
    op.drop_constraint(None, 'tai_khoan', type_='unique')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_constraint(None, 'quan_huyen', type_='foreignkey')
    op.drop_constraint(None, 'lk_vai_tro_nhan_vien', type_='foreignkey')
    op.drop_constraint(None, 'lk_vai_tro_nhan_vien', type_='foreignkey')
    # ### end Alembic commands ###
