"""update table tai_khoan

Revision ID: 9ac7b417a61d
Revises: cc88aee87574
Create Date: 2022-10-23 16:20:18.953616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ac7b417a61d'
down_revision = 'cc88aee87574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tai_khoan',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tai_khoan', sa.String(), nullable=False),
    sa.Column('mat_khau', sa.String(), nullable=False),
    sa.Column('dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('last_login_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tai_khoan')
    )
    op.create_foreign_key(None, 'users', 'tai_khoan', ['tai_khoan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_table('tai_khoan')
    # ### end Alembic commands ###
