"""update all table

Revision ID: a4acb86278f7
Revises: ff7f26daee27
Create Date: 2022-11-04 11:24:25.531491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4acb86278f7'
down_revision = 'ff7f26daee27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tai_khoan',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tai_khoan', sa.String(), nullable=False),
    sa.Column('mat_khau', sa.String(), nullable=False),
    sa.Column('dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('last_login_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tai_khoan')
    )
    op.create_table('users',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deactive_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ho', sa.String(length=80), nullable=True),
    sa.Column('ten', sa.String(length=80), nullable=True),
    sa.Column('ho_ten', sa.String(length=80), nullable=True),
    sa.Column('ten_khong_dau', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('ngay_sinh', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.String(), nullable=True),
    sa.Column('dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('ma_cong_dan', sa.String(length=80), nullable=True),
    sa.Column('ngay_cap', sa.BigInteger(), nullable=True),
    sa.Column('noi_cap', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('so_nha', sa.String(), nullable=True),
    sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vai_tro',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(length=80), nullable=False),
    sa.Column('ten_en', sa.String(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('lk_vai_tro_nhan_vien',
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('vai_tro_id', 'user_id')
    )
    op.create_table('records',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tuoi', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.BigInteger(), nullable=True),
    sa.Column('height', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.BigInteger(), nullable=True),
    sa.Column('ap_hi', sa.BigInteger(), nullable=True),
    sa.Column('ap_lo', sa.BigInteger(), nullable=True),
    sa.Column('chol', sa.BigInteger(), nullable=True),
    sa.Column('gluc', sa.BigInteger(), nullable=True),
    sa.Column('smoke', sa.BigInteger(), nullable=True),
    sa.Column('alco', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('lk_vai_tro_nhan_vien')
    op.drop_table('vai_tro')
    op.drop_table('users')
    op.drop_table('tai_khoan')
    # ### end Alembic commands ###
