"""update tables

Revision ID: a74f88975347
Revises: f59ebfd6752a
Create Date: 2022-10-22 16:51:10.310302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74f88975347'
down_revision = 'f59ebfd6752a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vai_tro', 'vai_tro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vai_tro', sa.Column('vai_tro', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
