"""

Revision ID: b607922e26d6
Revises: a8d06b4f6457
Create Date: 2022-11-27 18:10:48.733593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b607922e26d6'
down_revision = 'a8d06b4f6457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tai_khoan', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'tai_khoan', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tai_khoan', type_='foreignkey')
    op.drop_column('tai_khoan', 'user_id')
    # ### end Alembic commands ###
