"""

Revision ID: c130b280b9f5
Revises: 062fff1a9e86
Create Date: 2022-11-27 18:08:43.090395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c130b280b9f5'
down_revision = '062fff1a9e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tai_khoan',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tai_khoan', sa.String(), nullable=False),
    sa.Column('mat_khau', sa.String(), nullable=False),
    sa.Column('dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('last_login_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tai_khoan')
    )
    op.create_table('tinh_thanh',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.SMALLINT(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deactive_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ho', sa.String(length=80), nullable=True),
    sa.Column('ten', sa.String(length=80), nullable=True),
    sa.Column('ho_ten', sa.String(length=80), nullable=True),
    sa.Column('ten_khong_dau', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('ngay_sinh', sa.BigInteger(), nullable=True),
    sa.Column('dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('ma_cong_dan', sa.String(length=80), nullable=True),
    sa.Column('ngay_cap', sa.BigInteger(), nullable=True),
    sa.Column('noi_cap', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('tinh_thanh_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quan_huyen_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('xa_phuong_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('so_nha_hien_nay', sa.String(), nullable=True),
    sa.Column('tinh_thanh_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quan_huyen_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('xa_phuong_thuong_tru_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('so_nha_thuong_tru', sa.String(), nullable=True),
    sa.Column('tuoi', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.BigInteger(), nullable=True),
    sa.Column('height', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.BigInteger(), nullable=True),
    sa.Column('chol', sa.BigInteger(), nullable=True),
    sa.Column('gluc', sa.BigInteger(), nullable=True),
    sa.Column('smoke', sa.BigInteger(), nullable=True),
    sa.Column('alco', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quan_huyen_hien_nay_id'], ['quan_huyen.id'], ),
    sa.ForeignKeyConstraint(['quan_huyen_thuong_tru_id'], ['quan_huyen.id'], ),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ),
    sa.ForeignKeyConstraint(['tinh_thanh_hien_nay_id'], ['tinh_thanh.id'], ),
    sa.ForeignKeyConstraint(['tinh_thanh_thuong_tru_id'], ['tinh_thanh.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.ForeignKeyConstraint(['xa_phuong_hien_nay_id'], ['xa_phuong.id'], ),
    sa.ForeignKeyConstraint(['xa_phuong_thuong_tru_id'], ['xa_phuong.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vai_tro',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(length=80), nullable=False),
    sa.Column('ten_en', sa.String(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('lk_vai_tro_nhan_vien',
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('vai_tro_id', 'user_id')
    )
    op.create_table('quan_huyen',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tuoi', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.BigInteger(), nullable=True),
    sa.Column('height', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.BigInteger(), nullable=True),
    sa.Column('ap_hi', sa.BigInteger(), nullable=True),
    sa.Column('ap_lo', sa.BigInteger(), nullable=True),
    sa.Column('chol', sa.BigInteger(), nullable=True),
    sa.Column('gluc', sa.BigInteger(), nullable=True),
    sa.Column('smoke', sa.BigInteger(), nullable=True),
    sa.Column('alco', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tin_tuc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('ref_name', sa.String(), nullable=True),
    sa.Column('ref_logo', sa.String(), nullable=True),
    sa.Column('ref_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('accepted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xa_phuong',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('quanhuyen_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quanhuyen_id'], ['quan_huyen.id'], ),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xa_phuong')
    op.drop_table('tin_tuc')
    op.drop_table('records')
    op.drop_table('quan_huyen')
    op.drop_table('lk_vai_tro_nhan_vien')
    op.drop_table('vai_tro')
    op.drop_table('users')
    op.drop_table('tinh_thanh')
    op.drop_table('tai_khoan')
    # ### end Alembic commands ###
