"""update table tin_tuc

Revision ID: c8c939fd858f
Revises: e2d0b72aaecb
Create Date: 2022-11-21 15:18:48.609269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c939fd858f'
down_revision = 'e2d0b72aaecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tin_tuc', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'tin_tuc', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tin_tuc', 'users', ['accepted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    # ### end Alembic commands ###
