"""update table users

Revision ID: ca56bc25bb34
Revises: 312a5ac2eb46
Create Date: 2022-11-20 05:23:10.545360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca56bc25bb34'
down_revision = '312a5ac2eb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dia_chi')
    op.drop_column('users', 'so_nha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('so_nha', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dia_chi', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
