"""update table users

Revision ID: cc88aee87574
Revises: 6ea272fd5983
Create Date: 2022-10-22 17:40:15.064928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc88aee87574'
down_revision = '6ea272fd5983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deactive_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ho', sa.String(length=80), nullable=True),
    sa.Column('ten', sa.String(length=80), nullable=True),
    sa.Column('ho_ten', sa.String(length=80), nullable=True),
    sa.Column('ten_khong_dau', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('ngay_sinh', sa.BigInteger(), nullable=True),
    sa.Column('gioi_tinh', sa.String(), nullable=True),
    sa.Column('dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('ma_cong_dan', sa.String(length=80), nullable=True),
    sa.Column('ngay_cap', sa.BigInteger(), nullable=True),
    sa.Column('noi_cap', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('so_nha', sa.String(), nullable=True),
    sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
