"""update table user

Revision ID: d15fee898b3d
Revises: c3e33c06867f
Create Date: 2022-11-14 00:40:10.834543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15fee898b3d'
down_revision = 'c3e33c06867f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tuoi', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('height', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('chol', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('gluc', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('smoke', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('alco', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alco')
    op.drop_column('users', 'smoke')
    op.drop_column('users', 'gluc')
    op.drop_column('users', 'chol')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'tuoi')
    # ### end Alembic commands ###
