"""update table tintuc

Revision ID: e2d0b72aaecb
Revises: eb31c81b3beb
Create Date: 2022-11-21 03:19:55.187670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2d0b72aaecb'
down_revision = 'eb31c81b3beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tin_tuc', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'tin_tuc', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    op.drop_column('tin_tuc', 'user_id')
    # ### end Alembic commands ###
