"""update table tin_tuc

Revision ID: eb31c81b3beb
Revises: 445ab4f003e5
Create Date: 2022-11-21 03:07:06.177990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb31c81b3beb'
down_revision = '445ab4f003e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tin_tuc', sa.Column('views', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tin_tuc', 'views')
    # ### end Alembic commands ###
