"""Update cosokinhdoanh

Revision ID: 02db93c5fe0e
Revises: f0d2f8878406
Create Date: 2022-05-27 10:39:21.275425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02db93c5fe0e'
down_revision = 'f0d2f8878406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co_so_kinh_doanh',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nguoi_tncm_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('taikhoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ma_coso', sa.String(), nullable=True),
    sa.Column('ten_coso', sa.String(), nullable=True),
    sa.Column('ten_coso_khongdau', sa.String(), nullable=True),
    sa.Column('email_coso', sa.String(), nullable=True),
    sa.Column('dienthoai_coso', sa.String(), nullable=True),
    sa.Column('fax_coso', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('so_giay_phep', sa.String(), nullable=True),
    sa.Column('so_giay_phep_before', sa.String(), nullable=True),
    sa.Column('so_giay_phep_after', sa.String(), nullable=True),
    sa.Column('ngay_cap', sa.TIMESTAMP(), nullable=True),
    sa.Column('ngay_hieu_luc', sa.TIMESTAMP(), nullable=True),
    sa.Column('ngay_het_han', sa.TIMESTAMP(), nullable=True),
    sa.Column('co_quan_cap', sa.String(), nullable=True),
    sa.Column('dinhkem_chungchi', sa.String(), nullable=True),
    sa.Column('dinhkem_anh_chandung', sa.String(), nullable=True),
    sa.Column('dinhkem_vanbang_chuyenmon', sa.String(), nullable=True),
    sa.Column('dinhkem_xacnhan_congdan', sa.String(), nullable=True),
    sa.Column('dinhkem_files_khac', sa.String(), nullable=True),
    sa.Column('thoigian_yeucau_lienket', sa.TIMESTAMP(), nullable=True),
    sa.Column('thoigian_duyet_lienket', sa.TIMESTAMP(), nullable=True),
    sa.Column('ma_nguoiduyet', sa.String(), nullable=True),
    sa.Column('ten_nguoiduyet', sa.String(), nullable=True),
    sa.Column('thoigian_tuchoi_lienket', sa.TIMESTAMP(), nullable=True),
    sa.Column('lydo_tuchoi_lienket', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('diachi_coso', sa.String(), nullable=True),
    sa.Column('diachi_kho', sa.String(), nullable=True),
    sa.Column('ten_kinhdoanh', sa.String(), nullable=True),
    sa.Column('ten_kinhdoanh_khongdau', sa.String(), nullable=True),
    sa.Column('diachi_kinh_doanh', sa.String(), nullable=True),
    sa.Column('ten_nguoi_lien_he', sa.String(), nullable=True),
    sa.Column('chuc_danh_nguoi_lienhe', sa.String(), nullable=True),
    sa.Column('email_nguoi_lienhe', sa.String(), nullable=True),
    sa.Column('dien_thoai_nguoi_lienhe', sa.String(), nullable=True),
    sa.Column('fax_nguoi_lienhe', sa.String(), nullable=True),
    sa.Column('truc_thuoc', sa.String(), nullable=True),
    sa.Column('ten_truc_thuoc', sa.String(), nullable=True),
    sa.Column('ten_truc_thuoc_khong_dau', sa.String(), nullable=True),
    sa.Column('dia_chi_truc_thuoc', sa.String(), nullable=True),
    sa.Column('website_co_so', sa.String(), nullable=True),
    sa.Column('chung_minh_nguoi_lien_he', sa.String(), nullable=True),
    sa.Column('maso_doanh_nghiep_kinh_doanh', sa.String(), nullable=True),
    sa.Column('ma_so_doanh_nghiep_chi_nhanh', sa.String(), nullable=True),
    sa.Column('dia_chi_nguoi_lien_he', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_tncm_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['taikhoan_id'], ['tai_khoan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lk_loai_hinh_kinh_doanh',
    sa.Column('loai_hinh_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('co_so_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['co_so_kinh_doanh_id'], ['co_so_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['loai_hinh_kinh_doanh_id'], ['danhmuc_loai_hinh_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('loai_hinh_kinh_doanh_id', 'co_so_kinh_doanh_id')
    )
    op.create_table('lk_pham_vi_kinh_doanh',
    sa.Column('pham_vi_hoat_dong_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('co_so_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['co_so_kinh_doanh_id'], ['co_so_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['pham_vi_hoat_dong_kinh_doanh_id'], ['danhmuc_pham_vi_hoat_dong_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('pham_vi_hoat_dong_kinh_doanh_id', 'co_so_kinh_doanh_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_pham_vi_kinh_doanh')
    op.drop_table('lk_loai_hinh_kinh_doanh')
    op.drop_table('co_so_kinh_doanh')
    # ### end Alembic commands ###
