"""update

Revision ID: 08b2761029da
Revises: 8fc55efa98f5
Create Date: 2022-08-05 15:28:38.921375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b2761029da'
down_revision = '8fc55efa98f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nhan_vien', sa.Column('da_cap_chung_chi', sa.Boolean(), nullable=True))
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'noi_cong_tac')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'co_quan_cap')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ngaysinh')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'dia_cho_noi_congtac')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'so_giay_phep')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ma_doituong')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ma_thu_tuc')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'yeucau_cchnd')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ten_doi_tuong')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ma_hoso')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'macongdan')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ten_thu_tuc')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'noidung_dieuchinh')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'id_thu_tuc')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ten_vanbang_cm')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'gioitinh')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'loai_cap_chungchi')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'thaythe_cchnd')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ma_vanbang_cm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ma_vanbang_cm', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('thaythe_cchnd', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('loai_cap_chungchi', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('gioitinh', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ten_vanbang_cm', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('id_thu_tuc', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('noidung_dieuchinh', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ten_thu_tuc', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('macongdan', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ma_hoso', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ten_doi_tuong', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('yeucau_cchnd', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ma_thu_tuc', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ma_doituong', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('so_giay_phep', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('dia_cho_noi_congtac', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ngaysinh', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('co_quan_cap', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('noi_cong_tac', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('nhan_vien', 'da_cap_chung_chi')
    # ### end Alembic commands ###
