"""update

Revision ID: 0f4ce2d2a3a2
Revises: b3dbbc2a47e1
Create Date: 2022-06-09 15:17:49.942618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f4ce2d2a3a2'
down_revision = 'b3dbbc2a47e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co_so_thuc_hanh',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nhan_vien_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ma_co_so', sa.String(), nullable=True),
    sa.Column('ten_co_so', sa.String(), nullable=True),
    sa.Column('dia_chi_co_so', sa.String(), nullable=True),
    sa.Column('tu_ngay', sa.String(), nullable=True),
    sa.Column('den_ngay', sa.String(), nullable=True),
    sa.Column('chung_tu_dinh_kem', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=True),
    sa.Column('ten_nguoi_phu_trach', sa.String(), nullable=True),
    sa.Column('dien_thoai_nguoi_phu_trach', sa.String(), nullable=True),
    sa.Column('noi_dung_khac', sa.TEXT(), nullable=True),
    sa.Column('so_nha', sa.String(), nullable=True),
    sa.Column('quan_huyen_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tinh_thanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('xa_phuong_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('noi_dung_thuc_hanh', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['quan_huyen_id'], ['quan_huyen.id'], ),
    sa.ForeignKeyConstraint(['tinh_thanh_id'], ['tinh_thanh.id'], ),
    sa.ForeignKeyConstraint(['xa_phuong_id'], ['xa_phuong.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('danhmuc_vi_tri_hanh_nghe', sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'danhmuc_vi_tri_hanh_nghe', 'danhmuc_vi_tri_hanh_nghe', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'danhmuc_vi_tri_hanh_nghe', type_='foreignkey')
    op.drop_column('danhmuc_vi_tri_hanh_nghe', 'parent_id')
    op.drop_table('co_so_thuc_hanh')
    # ### end Alembic commands ###
