"""Update data table

Revision ID: 13717c6d7574
Revises: 6e66561567bd
Create Date: 2022-06-20 17:10:05.491892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13717c6d7574'
down_revision = '6e66561567bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('danhmuc_chung_chi', 'ho_ten')
    op.drop_column('danhmuc_chung_chi', 'ho')
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ngay_cap', sa.String(), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('noi_cap', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'noi_cap')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ngay_cap')
    op.add_column('danhmuc_chung_chi', sa.Column('ho', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('danhmuc_chung_chi', sa.Column('ho_ten', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
