"""update

Revision ID: 166ff77328a5
Revises: 0f4ce2d2a3a2
Create Date: 2022-06-13 14:04:14.573052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166ff77328a5'
down_revision = '0f4ce2d2a3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('hinh_thuc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'hinh_thuc')
    # ### end Alembic commands ###
