"""Update data table

Revision ID: 1929ef32deee
Revises: 1d8ad6d78364
Create Date: 2022-07-01 10:41:42.724233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1929ef32deee'
down_revision = '1d8ad6d78364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lk_loai_hinh_kinh_doanh_giay_phep',
    sa.Column('loai_hinh_kd_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('giay_phep_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['giay_phep_id'], ['giay_phep_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['loai_hinh_kd_id'], ['danhmuc_loai_hinh_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('loai_hinh_kd_id', 'giay_phep_id')
    )
    op.create_table('lk_pham_vi_kinh_doanh_giay_phep',
    sa.Column('pham_vi_kd_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('giay_phep_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['giay_phep_id'], ['giay_phep_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['pham_vi_kd_id'], ['danhmuc_pham_vi_hoat_dong_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('pham_vi_kd_id', 'giay_phep_id')
    )
    op.add_column('co_so_kinh_doanh', sa.Column('id_mapping', sa.String(), nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('so_nha_kinh_doanh', sa.String(), nullable=True))
    op.drop_column('co_so_kinh_doanh', 'ngay_hieu_luc')
    op.drop_column('co_so_kinh_doanh', 'co_quan_cap')
    op.drop_column('co_so_kinh_doanh', 'fax_coso')
    op.drop_column('co_so_kinh_doanh', 'thoigian_yeucau_lienket')
    op.drop_column('co_so_kinh_doanh', 'ma_nguoiduyet')
    op.drop_column('co_so_kinh_doanh', 'so_giay_phep_after')
    op.drop_column('co_so_kinh_doanh', 'thoigian_tuchoi_lienket')
    op.drop_column('co_so_kinh_doanh', 'ten_nguoiduyet')
    op.drop_column('co_so_kinh_doanh', 'lydo_tuchoi_lienket')
    op.drop_column('co_so_kinh_doanh', 'thoigian_duyet_lienket')
    op.drop_column('co_so_kinh_doanh', 'so_giay_phep_before')
    op.drop_column('co_so_kinh_doanh', 'ngay_het_han')
    op.drop_column('co_so_kinh_doanh', 'ngay_cap')
    op.drop_column('co_so_kinh_doanh', 'so_giay_phep')
    op.add_column('giay_phep_kinh_doanh', sa.Column('thoigian_yeucau_lienket', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('thoigian_duyet_lienket', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('thoigian_tuchoi_lienket', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('lydo_tuchoi_lienket', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('ma_nguoiduyet', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('ten_nguoiduyet', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('ten_httckd', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('dia_chi_tru_so', sa.String(), nullable=True))
    op.drop_column('giay_phep_kinh_doanh', 'dia_chi_co_so')
    op.drop_column('giay_phep_kinh_doanh', 'xa_phuong_co_so_id')
    op.drop_column('giay_phep_kinh_doanh', 'id_mapping')
    op.drop_column('giay_phep_kinh_doanh', 'nguoi_tcnm_so_cchn')
    op.drop_column('giay_phep_kinh_doanh', 'ten_co_so_en')
    op.drop_column('giay_phep_kinh_doanh', 'avatar_url')
    op.drop_column('giay_phep_kinh_doanh', 'nguoi_tcnm_ten_en')
    op.drop_column('giay_phep_kinh_doanh', 'ten_co_so')
    op.drop_column('giay_phep_kinh_doanh', 'dia_chi_kinh_doanh')
    op.drop_column('giay_phep_kinh_doanh', 'so_nha_co_so')
    op.drop_column('giay_phep_kinh_doanh', 'email_co_so')
    op.drop_column('giay_phep_kinh_doanh', 'quan_huyen_co_so_id')
    op.drop_column('giay_phep_kinh_doanh', 'fax_co_so')
    op.drop_column('giay_phep_kinh_doanh', 'so_nha_kinh_doanh')
    op.drop_column('giay_phep_kinh_doanh', 'dien_thoai_co_so')
    op.drop_column('giay_phep_kinh_doanh', 'tinh_thanh_co_so_id')
    op.drop_column('giay_phep_kinh_doanh', 'nguoi_tcnm_van_bang_id')
    op.drop_column('giay_phep_kinh_doanh', 'loai_hinh_kd')
    op.drop_column('giay_phep_kinh_doanh', 'ma_co_so')
    op.drop_column('giay_phep_kinh_doanh', 'nguoi_tcnm_ngay_cap')
    op.drop_column('giay_phep_kinh_doanh', 'nguoi_tcnm_ten')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giay_phep_kinh_doanh', sa.Column('nguoi_tcnm_ten', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('nguoi_tcnm_ngay_cap', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('ma_co_so', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('loai_hinh_kd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('nguoi_tcnm_van_bang_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('tinh_thanh_co_so_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('dien_thoai_co_so', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('so_nha_kinh_doanh', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('fax_co_so', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('quan_huyen_co_so_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('email_co_so', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('so_nha_co_so', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('dia_chi_kinh_doanh', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('ten_co_so', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('nguoi_tcnm_ten_en', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('ten_co_so_en', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('nguoi_tcnm_so_cchn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('id_mapping', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('xa_phuong_co_so_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('dia_chi_co_so', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('giay_phep_kinh_doanh', 'dia_chi_tru_so')
    op.drop_column('giay_phep_kinh_doanh', 'ten_httckd')
    op.drop_column('giay_phep_kinh_doanh', 'ten_nguoiduyet')
    op.drop_column('giay_phep_kinh_doanh', 'ma_nguoiduyet')
    op.drop_column('giay_phep_kinh_doanh', 'lydo_tuchoi_lienket')
    op.drop_column('giay_phep_kinh_doanh', 'thoigian_tuchoi_lienket')
    op.drop_column('giay_phep_kinh_doanh', 'thoigian_duyet_lienket')
    op.drop_column('giay_phep_kinh_doanh', 'thoigian_yeucau_lienket')
    op.add_column('co_so_kinh_doanh', sa.Column('so_giay_phep', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('ngay_cap', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('ngay_het_han', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('so_giay_phep_before', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('thoigian_duyet_lienket', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('lydo_tuchoi_lienket', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('ten_nguoiduyet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('thoigian_tuchoi_lienket', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('so_giay_phep_after', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('ma_nguoiduyet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('thoigian_yeucau_lienket', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('fax_coso', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('co_quan_cap', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('ngay_hieu_luc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('co_so_kinh_doanh', 'so_nha_kinh_doanh')
    op.drop_column('co_so_kinh_doanh', 'id_mapping')
    op.drop_table('lk_pham_vi_kinh_doanh_giay_phep')
    op.drop_table('lk_loai_hinh_kinh_doanh_giay_phep')
    # ### end Alembic commands ###
