"""update

Revision ID: 1b6a66bc17b8
Revises: a78c0cf77f5e
Create Date: 2022-08-04 09:25:50.352890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6a66bc17b8'
down_revision = 'a78c0cf77f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loai_ma_chung_chi', sa.Column('doi_tuong', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loai_ma_chung_chi', 'doi_tuong')
    # ### end Alembic commands ###
