"""update

Revision ID: 1cc0ee44b660
Revises: 7917af0cd98c
Create Date: 2022-05-20 15:17:36.936579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cc0ee44b660'
down_revision = '7917af0cd98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_nhan_vien_cchn')
    op.drop_table('lk_chung_chi_yeu_cau_chung_chi')
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('chung_chi_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'yeu_cau_chung_chi_hanh_nghe', 'danhmuc_chung_chi', ['chung_chi_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'chung_chi_id')
    op.create_table('lk_chung_chi_yeu_cau_chung_chi',
    sa.Column('danhmuc_chung_chi_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('cchn_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], name='lk_chung_chi_yeu_cau_chung_chi_cchn_id_fkey'),
    sa.ForeignKeyConstraint(['danhmuc_chung_chi_id'], ['danhmuc_chung_chi.id'], name='lk_chung_chi_yeu_cau_chung_chi_danhmuc_chung_chi_id_fkey'),
    sa.PrimaryKeyConstraint('danhmuc_chung_chi_id', 'cchn_id', name='lk_chung_chi_yeu_cau_chung_chi_pkey')
    )
    op.create_table('lk_nhan_vien_cchn',
    sa.Column('nhan_vien_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('cchn_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], name='lk_nhan_vien_cchn_cchn_id_fkey'),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], name='lk_nhan_vien_cchn_nhan_vien_id_fkey'),
    sa.PrimaryKeyConstraint('nhan_vien_id', 'cchn_id', name='lk_nhan_vien_cchn_pkey')
    )
    # ### end Alembic commands ###
