"""update

Revision ID: 1d8ad6d78364
Revises: b7a1986ba2af
Create Date: 2022-06-30 11:16:55.313176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d8ad6d78364'
down_revision = 'b7a1986ba2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giay_phep_kinh_doanh',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id_mapping', sa.String(), nullable=True),
    sa.Column('ma_co_so', sa.String(), nullable=True),
    sa.Column('ten_co_so', sa.String(), nullable=True),
    sa.Column('ten_co_so_en', sa.String(), nullable=True),
    sa.Column('email_co_so', sa.String(), nullable=True),
    sa.Column('dien_thoai_co_so', sa.String(), nullable=True),
    sa.Column('fax_co_so', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('so_giay_phep', sa.String(), nullable=True),
    sa.Column('so_giay_phep_before', sa.String(), nullable=True),
    sa.Column('so_giay_phep_after', sa.String(), nullable=True),
    sa.Column('ngay_cap', sa.BigInteger(), nullable=True),
    sa.Column('ngay_hieu_luc', sa.BigInteger(), nullable=True),
    sa.Column('ngay_het_han', sa.BigInteger(), nullable=True),
    sa.Column('co_quan_cap', sa.String(), nullable=True),
    sa.Column('so_giay_gps', sa.String(), nullable=True),
    sa.Column('nguoi_tcnm_ten', sa.String(), nullable=True),
    sa.Column('nguoi_tcnm_ten_en', sa.String(), nullable=True),
    sa.Column('nguoi_tcnm_so_cchn', sa.String(), nullable=True),
    sa.Column('nguoi_tcnm_ngay_cap', sa.BigInteger(), nullable=True),
    sa.Column('nguoi_tcnm_van_bang_id', sa.String(), nullable=True),
    sa.Column('tinh_thanh_co_so_id', sa.String(), nullable=True),
    sa.Column('quan_huyen_co_so_id', sa.String(), nullable=True),
    sa.Column('xa_phuong_co_so_id', sa.String(), nullable=True),
    sa.Column('so_nha_co_so', sa.String(), nullable=True),
    sa.Column('dia_chi_co_so', sa.String(), nullable=True),
    sa.Column('tinh_thanh_kinh_doanh_id', sa.String(), nullable=True),
    sa.Column('quan_huyen_kinh_doanh_id', sa.String(), nullable=True),
    sa.Column('xa_phuong_kinh_doanh_id', sa.String(), nullable=True),
    sa.Column('so_nha_kinh_doanh', sa.String(), nullable=True),
    sa.Column('dia_chi_kinh_doanh', sa.String(), nullable=True),
    sa.Column('ghi_chu', sa.String(), nullable=True),
    sa.Column('ghi_chu_loai_hinh_kd', sa.String(), nullable=True),
    sa.Column('ghi_chu_pham_vi_kd', sa.String(), nullable=True),
    sa.Column('loai_hinh_kd', sa.String(), nullable=True),
    sa.Column('ten_tru_so', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lk_loai_hinh_kinh_doanh_giay_phep',
    sa.Column('loai_hinh_kd_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('giay_phep_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['giay_phep_id'], ['giay_phep_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['loai_hinh_kd_id'], ['danhmuc_loai_hinh_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('loai_hinh_kd_id', 'giay_phep_id')
    )
    op.create_table('lk_pham_vi_kinh_doanh_giay_phep',
    sa.Column('pham_vi_kd_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('giay_phep_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['giay_phep_id'], ['giay_phep_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['pham_vi_kd_id'], ['danhmuc_pham_vi_hoat_dong_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('pham_vi_kd_id', 'giay_phep_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_pham_vi_kinh_doanh_giay_phep')
    op.drop_table('lk_loai_hinh_kinh_doanh_giay_phep')
    op.drop_table('giay_phep_kinh_doanh')
    # ### end Alembic commands ###
