"""update

Revision ID: 204a08b9e98a
Revises: feae299f1027
Create Date: 2022-05-20 14:48:17.055393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '204a08b9e98a'
down_revision = 'feae299f1027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danhmuc_chung_chi',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(length=80), nullable=True),
    sa.Column('ten_khong_dau', sa.String(length=80), nullable=True),
    sa.Column('ngay_sinh', sa.TIMESTAMP(), nullable=True),
    sa.Column('gioi_tinh', sa.TIMESTAMP(), nullable=True),
    sa.Column('ma_cong_dan', sa.String(length=80), nullable=True),
    sa.Column('ngay_cap', sa.TIMESTAMP(), nullable=True),
    sa.Column('noi_cap', sa.String(length=80), nullable=True),
    sa.Column('dien_thoai', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('dia_chi_thuong_tru', sa.String(), nullable=True),
    sa.Column('nam_tot_nghiep', sa.String(), nullable=True),
    sa.Column('so_giay_phep', sa.String(), nullable=True),
    sa.Column('co_quan_cap', sa.String(), nullable=True),
    sa.Column('nam_cap', sa.String(), nullable=True),
    sa.Column('ngay_hieu_luc', sa.TIMESTAMP(), nullable=True),
    sa.Column('ngay_het_han', sa.TIMESTAMP(), nullable=True),
    sa.Column('hinh_thuc_thi', sa.String(), nullable=True),
    sa.Column('noi_cong_tac', sa.String(), nullable=True),
    sa.Column('dia_chi_cong_tac', sa.String(), nullable=True),
    sa.Column('ghi_chu', sa.String(), nullable=True),
    sa.Column('ghi_chu_pham_vi_hanh_nghe', sa.String(), nullable=True),
    sa.Column('ghi_chu_vi_tri_hanh_nghe', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('so_thu_tu',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('so_thu_tu', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lk_noi_tot_nghiep_chung_chi',
    sa.Column('noi_tot_nghiep_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chung_chi_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['chung_chi_id'], ['danhmuc_chung_chi.id'], ),
    sa.ForeignKeyConstraint(['noi_tot_nghiep_id'], ['danhmuc_noi_tot_nghiep.id'], ),
    sa.PrimaryKeyConstraint('noi_tot_nghiep_id', 'chung_chi_id')
    )
    op.create_table('lk_pham_vi_hanh_nghe_chung_chi',
    sa.Column('pham_vi_hanh_nghe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chung_chi_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['chung_chi_id'], ['danhmuc_chung_chi.id'], ),
    sa.ForeignKeyConstraint(['pham_vi_hanh_nghe_id'], ['danhmuc_pham_vi_hoat_dong_chuyen_mon.id'], ),
    sa.PrimaryKeyConstraint('pham_vi_hanh_nghe_id', 'chung_chi_id')
    )
    op.create_table('lk_van_bang_chung_chi',
    sa.Column('van_bang_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chung_chi_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['chung_chi_id'], ['danhmuc_chung_chi.id'], ),
    sa.ForeignKeyConstraint(['van_bang_id'], ['danhmuc_van_bang_chuyen_mon.id'], ),
    sa.PrimaryKeyConstraint('van_bang_id', 'chung_chi_id')
    )
    op.create_table('lk_vi_tri_hanh_nghe_chung_chi',
    sa.Column('vi_tri_hanh_nghe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chung_chi_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['chung_chi_id'], ['danhmuc_chung_chi.id'], ),
    sa.ForeignKeyConstraint(['vi_tri_hanh_nghe_id'], ['danhmuc_vi_tri_hanh_nghe.id'], ),
    sa.PrimaryKeyConstraint('vi_tri_hanh_nghe_id', 'chung_chi_id')
    )
    op.drop_table('lk_pham_vi_hoat_dong_chuyen_mon_cchn')
    op.drop_table('lk_vi_tri_hanh_nghe_cchn')
    op.drop_constraint('yeu_cau_chung_chi_hanh_nghe_van_bang_chuyen_mon_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ngay_het_han')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ngay_hieu_luc')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'hinh_thuc')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'noi_cong_tac')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'so_giay_phep')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'co_quan_cap')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'van_bang_chuyen_mon_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('van_bang_chuyen_mon_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('co_quan_cap', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('so_giay_phep', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('noi_cong_tac', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('hinh_thuc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ngay_hieu_luc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ngay_het_han', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('yeu_cau_chung_chi_hanh_nghe_van_bang_chuyen_mon_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', 'danhmuc_van_bang_chuyen_mon', ['van_bang_chuyen_mon_id'], ['id'])
    op.create_table('lk_vi_tri_hanh_nghe_cchn',
    sa.Column('vi_tri_hanh_nghe_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('cchn_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], name='lk_vi_tri_hanh_nghe_cchn_cchn_id_fkey'),
    sa.ForeignKeyConstraint(['vi_tri_hanh_nghe_id'], ['danhmuc_vi_tri_hanh_nghe.id'], name='lk_vi_tri_hanh_nghe_cchn_vi_tri_hanh_nghe_id_fkey'),
    sa.PrimaryKeyConstraint('vi_tri_hanh_nghe_id', 'cchn_id', name='lk_vi_tri_hanh_nghe_cchn_pkey')
    )
    op.create_table('lk_pham_vi_hoat_dong_chuyen_mon_cchn',
    sa.Column('pham_vi_hoat_dong_chuyen_mon_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('cchn_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], name='lk_pham_vi_hoat_dong_chuyen_mon_cchn_cchn_id_fkey'),
    sa.ForeignKeyConstraint(['pham_vi_hoat_dong_chuyen_mon_id'], ['danhmuc_pham_vi_hoat_dong_chuyen_mon.id'], name='lk_pham_vi_hoat_dong_chuyen_m_pham_vi_hoat_dong_chuyen_mon_fkey'),
    sa.PrimaryKeyConstraint('pham_vi_hoat_dong_chuyen_mon_id', 'cchn_id', name='lk_pham_vi_hoat_dong_chuyen_mon_cchn_pkey')
    )
    op.drop_table('lk_vi_tri_hanh_nghe_chung_chi')
    op.drop_table('lk_van_bang_chung_chi')
    op.drop_table('lk_pham_vi_hanh_nghe_chung_chi')
    op.drop_table('lk_noi_tot_nghiep_chung_chi')
    op.drop_table('so_thu_tu')
    op.drop_table('danhmuc_chung_chi')
    # ### end Alembic commands ###
