"""Update data table loaimachungchi

Revision ID: 24e9d0990b36
Revises: 10ee1f1a675b
Create Date: 2022-06-17 17:39:20.712675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24e9d0990b36'
down_revision = '10ee1f1a675b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loai_ma_chung_chi',
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ma_chung_chi', sa.String(), nullable=True),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('ten_khong_dau', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=True),
    sa.Column('so_da_cap', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loai_magps',
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ma_gps', sa.String(), nullable=True),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('ten_khong_dau', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=True),
    sa.Column('so_da_cap', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('import_xa_phuong')
    op.drop_column('quan_huyen', 'ten')
    op.drop_column('quoc_gia', 'ten')
    op.drop_column('tinh_thanh', 'ten')
    op.drop_column('xa_phuong', 'ten')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xa_phuong', sa.Column('ten', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tinh_thanh', sa.Column('ten', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quoc_gia', sa.Column('ten', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quan_huyen', sa.Column('ten', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('import_xa_phuong',
    sa.Column('ma', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('ten', sa.VARCHAR(length=300), autoincrement=False, nullable=True)
    )
    op.drop_table('loai_magps')
    op.drop_table('loai_ma_chung_chi')
    # ### end Alembic commands ###
