"""update danhmuc_thu_tuc

Revision ID: 2bfd938400e2
Revises: c1eb0dadd475
Create Date: 2022-05-13 10:41:25.264597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bfd938400e2'
down_revision = 'c1eb0dadd475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danhmuc_thu_tuc',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('loai_thu_tuc', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('ten_khong_dau', sa.String(), nullable=True),
    sa.Column('linh_vuc', sa.String(), nullable=True),
    sa.Column('muc_do', sa.String(), nullable=True),
    sa.Column('co_quan_thuc_hien', sa.String(), nullable=True),
    sa.Column('thoi_gian_thuc_hien_bang_so', sa.String(), nullable=True),
    sa.Column('thoi_gian_giai_quyet', sa.String(), nullable=True),
    sa.Column('ket_qua_thuc_hien', sa.String(), nullable=True),
    sa.Column('le_phi_text', sa.String(), nullable=True),
    sa.Column('le_phi_number', sa.String(), nullable=True),
    sa.Column('cach_thuc_hien', sa.String(), nullable=True),
    sa.Column('thanh_phan_ho_so', sa.String(), nullable=True),
    sa.Column('can_cu_phap_ly', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('danhmuc_thu_tuc')
    # ### end Alembic commands ###
