"""Update data table

Revision ID: 2c3149e273ed
Revises: 20a51957fd0b
Create Date: 2022-06-14 12:03:14.104804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3149e273ed'
down_revision = '20a51957fd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bang_cap', sa.Column('hinh_thuc_dao_tao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bang_cap', 'hinh_thuc_dao_tao')
    # ### end Alembic commands ###
