"""Update data table

Revision ID: 35445c1908e8
Revises: b1b7f6dc6734
Create Date: 2022-07-15 09:43:48.511148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35445c1908e8'
down_revision = 'b1b7f6dc6734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_so_thuc_hanh', sa.Column('noi_dung_thuc_hanh', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('co_so_thuc_hanh_noi_dung_thuc_hanh_id_fkey', 'co_so_thuc_hanh', type_='foreignkey')
    op.drop_column('co_so_thuc_hanh', 'noi_dung_thuc_hanh_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_so_thuc_hanh', sa.Column('noi_dung_thuc_hanh_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('co_so_thuc_hanh_noi_dung_thuc_hanh_id_fkey', 'co_so_thuc_hanh', 'noi_dung_thuc_hanh', ['noi_dung_thuc_hanh_id'], ['id'])
    op.drop_column('co_so_thuc_hanh', 'noi_dung_thuc_hanh')
    # ### end Alembic commands ###
