"""update

Revision ID: 4049b0100e2e
Revises: 6557014a5d4a
Create Date: 2022-07-28 16:38:54.127190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4049b0100e2e'
down_revision = '6557014a5d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_vi_tri_hanh_nghe_yeucau_cchnd')
    op.create_foreign_key(None, 'yeu_cau_chung_chi_hanh_nghe', 'loai_ma_chung_chi', ['loai_ma_cchnd'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.create_table('lk_vi_tri_hanh_nghe_yeucau_cchnd',
    sa.Column('vi_tri_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('yeucau_cchnd_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vi_tri_id'], ['danhmuc_vi_tri_hanh_nghe.id'], name='lk_vi_tri_hanh_nghe_yeucau_cchnd_vi_tri_id_fkey'),
    sa.ForeignKeyConstraint(['yeucau_cchnd_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], name='lk_vi_tri_hanh_nghe_yeucau_cchnd_yeucau_cchnd_id_fkey'),
    sa.PrimaryKeyConstraint('vi_tri_id', 'yeucau_cchnd_id', name='lk_vi_tri_hanh_nghe_yeucau_cchnd_pkey')
    )
    # ### end Alembic commands ###
