"""vietpv9

Revision ID: 4265d250beaf
Revises: 680b622f4c6b
Create Date: 2022-08-15 15:21:04.288118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4265d250beaf'
down_revision = '680b622f4c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('co_so_kinh_doanh', 'loai_hinh_kinh_doanh')
    op.drop_column('co_so_kinh_doanh', 'dinhkem_files_khac')
    op.drop_column('co_so_kinh_doanh', 'dinhkem_anh_chandung')
    op.drop_column('co_so_kinh_doanh', 'dinhkem_vanbang_chuyenmon')
    op.drop_column('co_so_kinh_doanh', 'dinhkem_xacnhan_congdan')
    op.drop_column('co_so_kinh_doanh', 'pham_vi_kinh_doanh')
    op.drop_column('co_so_kinh_doanh', 'dinhkem_chungchi')
    op.add_column('giay_phep_kinh_doanh', sa.Column('dinhkem_chungchi', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('dinhkem_anh_chandung', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('dinhkem_vanbang_chuyenmon', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('dinhkem_xacnhan_congdan', sa.String(), nullable=True))
    op.add_column('giay_phep_kinh_doanh', sa.Column('dinhkem_files_khac', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giay_phep_kinh_doanh', 'dinhkem_files_khac')
    op.drop_column('giay_phep_kinh_doanh', 'dinhkem_xacnhan_congdan')
    op.drop_column('giay_phep_kinh_doanh', 'dinhkem_vanbang_chuyenmon')
    op.drop_column('giay_phep_kinh_doanh', 'dinhkem_anh_chandung')
    op.drop_column('giay_phep_kinh_doanh', 'dinhkem_chungchi')
    op.add_column('co_so_kinh_doanh', sa.Column('dinhkem_chungchi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('pham_vi_kinh_doanh', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('dinhkem_xacnhan_congdan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('dinhkem_vanbang_chuyenmon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('dinhkem_anh_chandung', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('dinhkem_files_khac', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('loai_hinh_kinh_doanh', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
