"""init db

Revision ID: 4b1b5bbbb8b2
Revises: 5577d25a8728
Create Date: 2022-05-04 13:17:08.499408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b1b5bbbb8b2'
down_revision = '5577d25a8728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nhan_vien',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('ho', sa.String(length=80), nullable=True),
    sa.Column('ten', sa.String(length=80), nullable=True),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('don_vi_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['don_vi_id'], ['don_vi.id'], ),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('thong_tin_don_vi')
    op.drop_table('nguoi_dat_hen')
    op.drop_table('dat_hen_kham_benh')
    op.drop_table('ho_so_nang_luc_don_vi')
    op.drop_table('nguoi_dung')
    op.drop_constraint('danh_muc_tin_tuc_short_key', 'danh_muc_tin_tuc', type_='unique')
    op.drop_constraint('tags_user_id_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'nhan_vien', ['user_id'], ['id'])
    op.add_column('tai_khoan', sa.Column('is_mobile_user', sa.Boolean(), nullable=True))
    op.drop_constraint('tai_khoan_mat_khau_key', 'tai_khoan', type_='unique')
    op.drop_constraint('tin_tuc_created_by_fkey', 'tin_tuc', type_='foreignkey')
    op.create_foreign_key(None, 'tin_tuc', 'nhan_vien', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tin_tuc', type_='foreignkey')
    op.create_foreign_key('tin_tuc_created_by_fkey', 'tin_tuc', 'nguoi_dung', ['created_by'], ['id'])
    op.create_unique_constraint('tai_khoan_mat_khau_key', 'tai_khoan', ['mat_khau'])
    op.drop_column('tai_khoan', 'is_mobile_user')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_user_id_fkey', 'tags', 'nguoi_dung', ['user_id'], ['id'])
    op.create_unique_constraint('danh_muc_tin_tuc_short_key', 'danh_muc_tin_tuc', ['short'])
    op.create_table('nguoi_dung',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('ho', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('ten', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('dia_chi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('so_dien_thoai', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('don_vi_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('vai_tro_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('tai_khoan_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['don_vi_id'], ['don_vi.id'], name='nguoi_dung_don_vi_id_fkey'),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], name='nguoi_dung_tai_khoan_id_fkey'),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], name='nguoi_dung_vai_tro_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nguoi_dung_pkey')
    )
    op.create_table('ho_so_nang_luc_don_vi',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('don_vi_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('ten_don_vi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tong_so_giuong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_benh_nhan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_dang_dieu_tri', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_cong_don', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('khong_benh_nen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ko_benh_nen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_nhap_moi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_chuyen_tang_tren', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_chuyen_tang_duoi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_tong_nvy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_tre_em', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_phu_nu_mang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_khac', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don_tong_nvy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_benh_nhan_khong_mac_covid_19_tu_vong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_du_kien_xet_nghiem_ngay_hom_sau', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ecmo_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ecmo_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc_mau_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc_mau_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_xam_lan_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_xam_lan_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_hfnc_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_hfnc_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_cpap_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_cpap_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_bipap_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_khong_xam_lan_bipap_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_giuong_tho_oxy_thuong_gong_kinh_mat_na_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_giuong_tho_oxy_thuong_gong_kinh_mat_na_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_co_oxy_tho_oxy_thuong_tho_may_tho_hfnc_cpap_tong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_co_oxy_tho_oxy_thuong_tho_may_tho_hfnc_cpap_dang_su_dung', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ca_mac_tang_1_luy_ke', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ca_mac_tang_1_hom_nay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('khoi_benh_tang_1_luy_ke', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('khoi_benh_tang_1_hom_nay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('giuong_benh_tang_1_luy_ke', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('giuong_benh_tang_1_hom_nay', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tang', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at_view', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['don_vi_id'], ['don_vi.id'], name='ho_so_nang_luc_don_vi_don_vi_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ho_so_nang_luc_don_vi_pkey')
    )
    op.create_table('dat_hen_kham_benh',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('ten_nguoi_dat_hen', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nguoi_dat_hen_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['nguoi_dat_hen_id'], ['nguoi_dat_hen.id'], name='dat_hen_kham_benh_nguoi_dat_hen_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dat_hen_kham_benh_pkey')
    )
    op.create_table('nguoi_dat_hen',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('ho', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('ten', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('dia_chi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tai_khoan_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('so_dien_thoai', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], name='nguoi_dat_hen_tai_khoan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nguoi_dat_hen_pkey')
    )
    op.create_table('thong_tin_don_vi',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('tong_so_giuong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_benh_nhan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_dang_dieu_tri', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_ca_pcr_cong_don', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_nhap_moi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_chuyen_tang_tren', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tinh_hinh_tiep_nhan_24h_chuyen_tang_duoi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_trong_24h', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_xuat_vien_cong_don', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_trong_24h', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_ca_tu_vong_cong_don', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chi_tieu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_ecmo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_loc_mau', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_may_tho_hfnc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_may_tho_cpap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_may_tho_bipap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_giuong_tho_oxy_thuong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tong_so_giuong_co_oxy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ecmo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc_mau', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_hfnc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_cpap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('may_tho_bipap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_giuong_tho_oxy_thuong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('so_giuong_co_oxy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='thong_tin_don_vi_pkey')
    )
    op.drop_table('nhan_vien')
    # ### end Alembic commands ###
