"""Update data table

Revision ID: 539e55bf7e0c
Revises: 8c3b1e98de58
Create Date: 2022-07-05 09:39:31.741844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '539e55bf7e0c'
down_revision = '8c3b1e98de58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nhan_vien', sa.Column('quan_huyen_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('nhan_vien', sa.Column('tinh_thanh_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('nhan_vien', sa.Column('xa_phuong_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('nhan_vien', sa.Column('van_bang_chuyen_mon_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('nhan_vien', sa.Column('noi_tot_nghiep_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('nhan_vien', sa.Column('nam_tot_nghiep', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'nhan_vien', 'xa_phuong', ['xa_phuong_id'], ['id'])
    op.create_foreign_key(None, 'nhan_vien', 'tinh_thanh', ['tinh_thanh_id'], ['id'])
    op.create_foreign_key(None, 'nhan_vien', 'quan_huyen', ['quan_huyen_id'], ['id'])
    op.create_foreign_key(None, 'nhan_vien', 'danhmuc_noi_tot_nghiep', ['noi_tot_nghiep_id'], ['id'])
    op.create_foreign_key(None, 'nhan_vien', 'danhmuc_van_bang_chuyen_mon', ['van_bang_chuyen_mon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nhan_vien', type_='foreignkey')
    op.drop_constraint(None, 'nhan_vien', type_='foreignkey')
    op.drop_constraint(None, 'nhan_vien', type_='foreignkey')
    op.drop_constraint(None, 'nhan_vien', type_='foreignkey')
    op.drop_constraint(None, 'nhan_vien', type_='foreignkey')
    op.drop_column('nhan_vien', 'nam_tot_nghiep')
    op.drop_column('nhan_vien', 'noi_tot_nghiep_id')
    op.drop_column('nhan_vien', 'van_bang_chuyen_mon_id')
    op.drop_column('nhan_vien', 'xa_phuong_id')
    op.drop_column('nhan_vien', 'tinh_thanh_id')
    op.drop_column('nhan_vien', 'quan_huyen_id')
    # ### end Alembic commands ###
