"""update bangcap

Revision ID: 5e7093371c2e
Revises: 2d6b71a5a02d
Create Date: 2022-05-12 15:27:56.226083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e7093371c2e'
down_revision = '2d6b71a5a02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bang_cap',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nhan_vien_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('van_bang_chuyen_mon_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('so_hieu', sa.String(), nullable=True),
    sa.Column('loai_hinh_dao_tao', sa.String(), nullable=True),
    sa.Column('noi_tot_nghiep_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('nganh_dao_tao', sa.String(), nullable=True),
    sa.Column('xep_hang', sa.String(), nullable=True),
    sa.Column('danh_hieu', sa.String(), nullable=True),
    sa.Column('ngay_cap', sa.TIMESTAMP(), nullable=True),
    sa.Column('chung_tu_dinh_kem', sa.String(), nullable=True),
    sa.Column('ghi_chu', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['noi_tot_nghiep_id'], ['danhmuc_noi_tot_nghiep.id'], ),
    sa.ForeignKeyConstraint(['van_bang_chuyen_mon_id'], ['danhmuc_van_bang_chuyen_mon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bang_cap')
    # ### end Alembic commands ###
