"""update

Revision ID: 6557014a5d4a
Revises: d22cb10f7ae7
Create Date: 2022-07-28 10:54:10.261063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6557014a5d4a'
down_revision = 'd22cb10f7ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ngay_hieu_luc', sa.BigInteger(), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ngay_het_han', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ngay_het_han')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ngay_hieu_luc')
    # ### end Alembic commands ###
