"""update

Revision ID: 680b622f4c6b
Revises: 08b2761029da
Create Date: 2022-08-05 15:37:12.076266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680b622f4c6b'
down_revision = '08b2761029da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nhan_vien', sa.Column('da_cap_chung_chi', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nhan_vien', 'da_cap_chung_chi')
    # ### end Alembic commands ###
