"""update

Revision ID: 6e909b4cce46
Revises: dab4603f1644
Create Date: 2022-07-21 10:39:53.908717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e909b4cce46'
down_revision = 'dab4603f1644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('yeu_cau_chung_chi_hanh_nghe_quan_huyen_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint('yeu_cau_chung_chi_hanh_nghe_quan_huyen_hien_nay_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint('yeu_cau_chung_chi_hanh_nghe_xa_phuong_hien_nay_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint('yeu_cau_chung_chi_hanh_nghe_xa_phuong_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint('yeu_cau_chung_chi_hanh_nghe_tinh_thanh_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint('yeu_cau_chung_chi_hanh_nghe_tinh_thanh_hien_nay_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'dia_chi')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'quan_huyen_hien_nay_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'xa_phuong_hien_nay_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'tinh_thanh_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'xa_phuong_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'tinh_thanh_hien_nay_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'quan_huyen_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'dia_chi_thuong_tru')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('dia_chi_thuong_tru', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('quan_huyen_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('tinh_thanh_hien_nay_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('xa_phuong_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('tinh_thanh_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('xa_phuong_hien_nay_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('quan_huyen_hien_nay_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('dia_chi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('yeu_cau_chung_chi_hanh_nghe_tinh_thanh_hien_nay_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', 'tinh_thanh', ['tinh_thanh_hien_nay_id'], ['id'])
    op.create_foreign_key('yeu_cau_chung_chi_hanh_nghe_tinh_thanh_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', 'tinh_thanh', ['tinh_thanh_id'], ['id'])
    op.create_foreign_key('yeu_cau_chung_chi_hanh_nghe_xa_phuong_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', 'xa_phuong', ['xa_phuong_id'], ['id'])
    op.create_foreign_key('yeu_cau_chung_chi_hanh_nghe_xa_phuong_hien_nay_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', 'xa_phuong', ['xa_phuong_hien_nay_id'], ['id'])
    op.create_foreign_key('yeu_cau_chung_chi_hanh_nghe_quan_huyen_hien_nay_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', 'quan_huyen', ['quan_huyen_hien_nay_id'], ['id'])
    op.create_foreign_key('yeu_cau_chung_chi_hanh_nghe_quan_huyen_id_fkey', 'yeu_cau_chung_chi_hanh_nghe', 'quan_huyen', ['quan_huyen_id'], ['id'])
    # ### end Alembic commands ###
