"""update

Revision ID: 7917af0cd98c
Revises: 204a08b9e98a
Create Date: 2022-05-20 14:54:18.242328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7917af0cd98c'
down_revision = '204a08b9e98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lk_chung_chi_yeu_cau_chung_chi',
    sa.Column('danhmuc_chung_chi_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cchn_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['danhmuc_chung_chi_id'], ['danhmuc_chung_chi.id'], ),
    sa.PrimaryKeyConstraint('danhmuc_chung_chi_id', 'cchn_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_chung_chi_yeu_cau_chung_chi')
    # ### end Alembic commands ###
