"""UPDATE TABLE LichSuChungChi

Revision ID: 79a04bec3feb
Revises: ba397a316f18
Create Date: 2022-06-09 09:57:59.769393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79a04bec3feb'
down_revision = 'ba397a316f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lich_su_chung_chi',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('loai_thay_doi', sa.String(), nullable=True),
    sa.Column('noi_dung_thay_doi', sa.String(), nullable=True),
    sa.Column('ngay_thay_doi', sa.String(), nullable=True),
    sa.Column('so_quyet_dinh', sa.String(), nullable=True),
    sa.Column('chung_tu_dinh_kem', sa.String(), nullable=True),
    sa.Column('chung_chi_cu', sa.String(), nullable=True),
    sa.Column('chung_chi_moi', sa.String(), nullable=True),
    sa.Column('chuyen_vien_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('lanh_dao_id', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chuyen_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lich_su_chung_chi')
    # ### end Alembic commands ###
