"""update Table 

Revision ID: 7bac9cb8cbd1
Revises: 971daa5d75c6
Create Date: 2022-05-12 09:20:14.709254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bac9cb8cbd1'
down_revision = '971daa5d75c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danhmuc_hoi_dong',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ma_hoi_dong', sa.String(), nullable=True),
    sa.Column('ten_hoi_dong', sa.String(), nullable=True),
    sa.Column('ten_khong_dau', sa.String(), nullable=True),
    sa.Column('ngay_thanh_lap', sa.TIMESTAMP(), nullable=True),
    sa.Column('ten_nguoi_phu_trach', sa.String(length=80), nullable=True),
    sa.Column('trang_thai', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('quan_huyen', 'ten')
    op.drop_column('quan_huyen', 'ten_tieng_anh')
    op.drop_column('quoc_gia', 'ten')
    op.drop_column('quoc_gia', 'ten_tieng_anh')
    op.drop_column('tinh_thanh', 'ten')
    op.drop_column('tinh_thanh', 'ten_tieng_anh')
    op.drop_column('xa_phuong', 'ten')
    op.drop_column('xa_phuong', 'ten_tieng_anh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xa_phuong', sa.Column('ten_tieng_anh', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('xa_phuong', sa.Column('ten', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('tinh_thanh', sa.Column('ten_tieng_anh', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('tinh_thanh', sa.Column('ten', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('quoc_gia', sa.Column('ten_tieng_anh', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('quoc_gia', sa.Column('ten', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('quan_huyen', sa.Column('ten_tieng_anh', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('quan_huyen', sa.Column('ten', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_table('danhmuc_hoi_dong')
    # ### end Alembic commands ###
