"""Update chungnhancoso

Revision ID: 7e0a61a540e1
Revises: d5ef2bc51220
Create Date: 2022-05-27 14:34:44.778325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e0a61a540e1'
down_revision = 'd5ef2bc51220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chung_nhan_thuc_hanh_co_so',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('so_giaychungnhan', sa.String(), nullable=True),
    sa.Column('ngay_kiemtra', sa.TIMESTAMP(), nullable=True),
    sa.Column('ngay_cap', sa.TIMESTAMP(), nullable=True),
    sa.Column('ngay_hieu_luc', sa.TIMESTAMP(), nullable=True),
    sa.Column('ngay_het_han', sa.TIMESTAMP(), nullable=True),
    sa.Column('diachi', sa.String(), nullable=True),
    sa.Column('dinhkem_giaychungnhan', sa.String(), nullable=True),
    sa.Column('coso_kinhdoanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coso_kinhdoanh_id'], ['co_so_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chung_nhan_thuc_hanh_co_so')
    # ### end Alembic commands ###
