"""vietpv9

Revision ID: 7fe52eff6e30
Revises: 93ff1447d57e
Create Date: 2022-08-16 14:17:44.670910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fe52eff6e30'
down_revision = '93ff1447d57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lk_vai_tro_to_chuc',
    sa.Column('vai_tro_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('to_chuc_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['to_chuc_id'], ['co_so_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('vai_tro_id', 'to_chuc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_vai_tro_to_chuc')
    # ### end Alembic commands ###
