"""Update data table

Revision ID: 8c3b1e98de58
Revises: cea95701006d
Create Date: 2022-07-05 08:33:29.158613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3b1e98de58'
down_revision = 'cea95701006d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chung_chi_hanh_nghe', sa.Column('thoi_gian_yeu_cau_lien_ket', sa.BigInteger(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('thoi_gian_duyet_lien_ket', sa.BigInteger(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('thoi_gian_tu_choi_lien_ket', sa.BigInteger(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('ngay_hieu_luc', sa.BigInteger(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('ngay_quyet_dinh', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chung_chi_hanh_nghe', 'ngay_quyet_dinh')
    op.drop_column('chung_chi_hanh_nghe', 'ngay_hieu_luc')
    op.drop_column('chung_chi_hanh_nghe', 'thoi_gian_tu_choi_lien_ket')
    op.drop_column('chung_chi_hanh_nghe', 'thoi_gian_duyet_lien_ket')
    op.drop_column('chung_chi_hanh_nghe', 'thoi_gian_yeu_cau_lien_ket')
    # ### end Alembic commands ###
