"""Update data duocsichuagiayphep

Revision ID: 8ec4c5290c04
Revises: 2c3149e273ed
Create Date: 2022-06-15 15:30:07.905327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec4c5290c04'
down_revision = '2c3149e273ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duoc_si_co_so_chua_giay_phep', sa.Column('ho_ten_khong_dau', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duoc_si_co_so_chua_giay_phep', 'ho_ten_khong_dau')
    # ### end Alembic commands ###
