"""vietpv9

Revision ID: 93ff1447d57e
Revises: a56cbdc904d0
Create Date: 2022-08-16 11:30:57.135309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ff1447d57e'
down_revision = 'a56cbdc904d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_so_kinh_doanh', sa.Column('da_cap_giay_phep', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('co_so_kinh_doanh', 'da_cap_giay_phep')
    # ### end Alembic commands ###
