"""Update data table gps

Revision ID: 94dee5e6edbe
Revises: 93ef583e83cc
Create Date: 2022-06-15 17:19:06.310895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dee5e6edbe'
down_revision = '93ef583e83cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loai_magps', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('loai_magps', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('loai_magps', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('loai_magps', sa.Column('deleted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loai_magps', 'deleted_by')
    op.drop_column('loai_magps', 'deleted')
    op.drop_column('loai_magps', 'updated_by')
    op.drop_column('loai_magps', 'created_by')
    # ### end Alembic commands ###
