"""update

Revision ID: 971daa5d75c6
Revises: ea9ceb4fd277
Create Date: 2022-05-11 15:38:20.978710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '971daa5d75c6'
down_revision = 'ea9ceb4fd277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quoc_gia',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tinh_thanh',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('quocgia_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quocgia_id'], ['quoc_gia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quan_huyen',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xa_phuong',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('ma', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.String(), nullable=True),
    sa.Column('loai', sa.String(), nullable=True),
    sa.Column('quanhuyen_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tinhthanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quanhuyen_id'], ['quan_huyen.id'], ),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinh_thanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xa_phuong')
    op.drop_table('quan_huyen')
    op.drop_table('tinh_thanh')
    op.drop_table('quoc_gia')
    # ### end Alembic commands ###
