"""vietpv9

Revision ID: a56cbdc904d0
Revises: 4265d250beaf
Create Date: 2022-08-16 09:33:19.428190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56cbdc904d0'
down_revision = '4265d250beaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_so_kinh_doanh', sa.Column('diachi_tructhuoc', sa.String(), nullable=True))
    op.add_column('co_so_kinh_doanh', sa.Column('ma_tructhuoc', sa.String(), nullable=True))
    op.drop_column('co_so_kinh_doanh', 'dia_chi_truc_thuoc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_so_kinh_doanh', sa.Column('dia_chi_truc_thuoc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('co_so_kinh_doanh', 'ma_tructhuoc')
    op.drop_column('co_so_kinh_doanh', 'diachi_tructhuoc')
    # ### end Alembic commands ###
