"""update

Revision ID: a78c0cf77f5e
Revises: c99c03e99fe6
Create Date: 2022-08-03 16:08:36.895129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78c0cf77f5e'
down_revision = 'c99c03e99fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duoc_si_co_so_chua_giay_phep', 'phut_bat_dau')
    op.drop_column('duoc_si_co_so_chua_giay_phep', 'ngay_bat_dau')
    op.drop_column('duoc_si_co_so_chua_giay_phep', 'vi_tri_lam_viec_before')
    op.drop_column('duoc_si_co_so_chua_giay_phep', 'ngay_ket_thuc')
    op.drop_column('duoc_si_co_so_chua_giay_phep', 'gio_bat_dau')
    op.drop_column('duoc_si_co_so_chua_giay_phep', 'gio_ket_thuc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duoc_si_co_so_chua_giay_phep', sa.Column('gio_ket_thuc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('duoc_si_co_so_chua_giay_phep', sa.Column('gio_bat_dau', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('duoc_si_co_so_chua_giay_phep', sa.Column('ngay_ket_thuc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('duoc_si_co_so_chua_giay_phep', sa.Column('vi_tri_lam_viec_before', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('duoc_si_co_so_chua_giay_phep', sa.Column('ngay_bat_dau', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('duoc_si_co_so_chua_giay_phep', sa.Column('phut_bat_dau', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
