"""Update data table

Revision ID: bdc59d550c32
Revises: f5b77884c468
Create Date: 2022-07-12 10:50:57.057102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdc59d550c32'
down_revision = 'f5b77884c468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('quan_huyen_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('tinh_thanh_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('xa_phuong_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('dia_chi_thuong_tru', sa.String(), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('quan_huyen_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('tinh_thanh_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('xa_phuong_hien_nay_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('dia_chi', sa.String(), nullable=True))
    op.create_foreign_key(None, 'yeu_cau_chung_chi_hanh_nghe', 'quan_huyen', ['quan_huyen_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'yeu_cau_chung_chi_hanh_nghe', 'tinh_thanh', ['tinh_thanh_id'], ['id'])
    op.create_foreign_key(None, 'yeu_cau_chung_chi_hanh_nghe', 'quan_huyen', ['quan_huyen_id'], ['id'])
    op.create_foreign_key(None, 'yeu_cau_chung_chi_hanh_nghe', 'xa_phuong', ['xa_phuong_hien_nay_id'], ['id'])
    op.create_foreign_key(None, 'yeu_cau_chung_chi_hanh_nghe', 'xa_phuong', ['xa_phuong_id'], ['id'])
    op.create_foreign_key(None, 'yeu_cau_chung_chi_hanh_nghe', 'tinh_thanh', ['tinh_thanh_hien_nay_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint(None, 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint(None, 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint(None, 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint(None, 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_constraint(None, 'yeu_cau_chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'dia_chi')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'xa_phuong_hien_nay_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'tinh_thanh_hien_nay_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'quan_huyen_hien_nay_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'dia_chi_thuong_tru')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'xa_phuong_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'tinh_thanh_id')
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'quan_huyen_id')
    # ### end Alembic commands ###
