"""update bangcap

Revision ID: c1eb0dadd475
Revises: 5e7093371c2e
Create Date: 2022-05-12 15:47:11.765312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1eb0dadd475'
down_revision = '5e7093371c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bang_cap', sa.Column('trang_thai', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bang_cap', 'trang_thai')
    # ### end Alembic commands ###
