"""Update data table

Revision ID: c375a2a1539a
Revises: 1929ef32deee
Create Date: 2022-07-01 15:30:13.796472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c375a2a1539a'
down_revision = '1929ef32deee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giay_phep_kinh_doanh', sa.Column('co_so_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'giay_phep_kinh_doanh', 'co_so_kinh_doanh', ['co_so_kinh_doanh_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'giay_phep_kinh_doanh', type_='foreignkey')
    op.drop_column('giay_phep_kinh_doanh', 'co_so_kinh_doanh_id')
    # ### end Alembic commands ###
