"""Update data table

Revision ID: c530c7de9a90
Revises: c375a2a1539a
Create Date: 2022-07-04 15:59:49.343099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c530c7de9a90'
down_revision = 'c375a2a1539a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bang_cap', sa.Column('nam_cap', sa.Integer(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('hinh_thuc_thi', sa.String(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('ghi_chu', sa.String(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('ghi_chu_pham_vi_hanh_nghe', sa.String(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('ghi_chu_vi_tri_hanh_nghe', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'chung_chi_hanh_nghe', ['nhan_vien_id'])
    op.drop_column('chung_chi_hanh_nghe', 'hinh_thuc')
    op.add_column('nhan_vien', sa.Column('id_mapping', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nhan_vien', 'id_mapping')
    op.add_column('chung_chi_hanh_nghe', sa.Column('hinh_thuc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chung_chi_hanh_nghe', type_='unique')
    op.drop_column('chung_chi_hanh_nghe', 'ghi_chu_vi_tri_hanh_nghe')
    op.drop_column('chung_chi_hanh_nghe', 'ghi_chu_pham_vi_hanh_nghe')
    op.drop_column('chung_chi_hanh_nghe', 'ghi_chu')
    op.drop_column('chung_chi_hanh_nghe', 'hinh_thuc_thi')
    op.drop_column('bang_cap', 'nam_cap')
    # ### end Alembic commands ###
