"""update

Revision ID: c99c03e99fe6
Revises: a8a45609cb16
Create Date: 2022-07-29 11:29:08.130847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99c03e99fe6'
down_revision = 'a8a45609cb16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yeu_cau_chung_chi_hanh_nghe', sa.Column('ngay_cap_cchnd_cu', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yeu_cau_chung_chi_hanh_nghe', 'ngay_cap_cchnd_cu')
    # ### end Alembic commands ###
