"""UPDATE TABLE thanhPhanHoSo

Revision ID: d19b84548f26
Revises: ecfa7c6a7d9f
Create Date: 2022-06-03 17:35:17.027989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19b84548f26'
down_revision = 'ecfa7c6a7d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('danhmuc_thu_tuc', 'thanh_phan_ho_so')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('danhmuc_thu_tuc', sa.Column('thanh_phan_ho_so', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
