"""Update data table

Revision ID: d93e8833bbc8
Revises: 164329c4fcd5
Create Date: 2022-06-21 10:55:15.764908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93e8833bbc8'
down_revision = '164329c4fcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chung_chi_hanh_nghe', sa.Column('ngay_cap', sa.String(), nullable=True))
    op.add_column('chung_chi_hanh_nghe', sa.Column('noi_cap', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chung_chi_hanh_nghe', 'noi_cap')
    op.drop_column('chung_chi_hanh_nghe', 'ngay_cap')
    # ### end Alembic commands ###
