"""update db

Revision ID: da26021e6987
Revises: 1f89a92c89ef
Create Date: 2022-05-04 17:27:53.763721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da26021e6987'
down_revision = '1f89a92c89ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khach_hang',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ho_ten', sa.String(), nullable=True),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('ma_bao_hiem', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('goi_y')
    op.add_column('tai_khoan', sa.Column('is_customer', sa.Boolean(), nullable=True))
    op.add_column('tai_khoan', sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tai_khoan', 'last_login_at')
    op.drop_column('tai_khoan', 'is_customer')
    op.create_table('goi_y',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tu_khoa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('loai_tu_goi_y', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lan_tim_kiem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trang_thai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='goi_y_pkey')
    )
    op.drop_table('khach_hang')
    # ### end Alembic commands ###
