"""UPDATE TABLE

Revision ID: e002d9c09344
Revises: d19b84548f26
Create Date: 2022-06-03 18:17:19.288272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e002d9c09344'
down_revision = 'd19b84548f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danhmuc_thanh_phan_ho_so',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ma_tp_ho_so', sa.String(), nullable=True),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('ten_khong_dau', sa.String(), nullable=True),
    sa.Column('ma_thu_tuc', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ma_thu_tuc'], ['danhmuc_thu_tuc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('danhmuc_thu_tuc', sa.Column('thanh_phan_ho_so', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('danhmuc_thu_tuc', 'thanh_phan_ho_so')
    op.drop_table('danhmuc_thanh_phan_ho_so')
    # ### end Alembic commands ###
