"""update danhmucphamvihdkinhdoanh ten_in 

Revision ID: e74376547383
Revises: aeb6e4246046
Create Date: 2022-05-25 10:09:22.627017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74376547383'
down_revision = 'aeb6e4246046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('danhmuc_pham_vi_hoat_dong_kinh_doanh', sa.Column('ten_in', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('danhmuc_pham_vi_hoat_dong_kinh_doanh', 'ten_in')
    # ### end Alembic commands ###
