"""update

Revision ID: ef26eb46dd5e
Revises: f27152e34b4e
Create Date: 2022-05-24 11:05:05.997825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef26eb46dd5e'
down_revision = 'f27152e34b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thong_bao_user')
    op.drop_table('lk_van_bang_chuyen_mon_cchn')
    op.drop_table('thong_bao')
    op.add_column('chung_chi_hanh_nghe', sa.Column('van_bang_chuyen_mon_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'chung_chi_hanh_nghe', 'danhmuc_van_bang_chuyen_mon', ['van_bang_chuyen_mon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chung_chi_hanh_nghe', type_='foreignkey')
    op.drop_column('chung_chi_hanh_nghe', 'van_bang_chuyen_mon_id')
    op.create_table('thong_bao',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('tieu_de', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('noi_dung', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('loai', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trang_thai', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='thong_bao_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('lk_van_bang_chuyen_mon_cchn',
    sa.Column('van_bang_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('cchn_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['chung_chi_hanh_nghe.id'], name='lk_van_bang_chuyen_mon_cchn_cchn_id_fkey'),
    sa.ForeignKeyConstraint(['van_bang_id'], ['danhmuc_van_bang_chuyen_mon.id'], name='lk_van_bang_chuyen_mon_cchn_van_bang_id_fkey'),
    sa.PrimaryKeyConstraint('van_bang_id', 'cchn_id', name='lk_van_bang_chuyen_mon_cchn_pkey')
    )
    op.create_table('thong_bao_user',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('thong_bao_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('notify_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['thong_bao_id'], ['thong_bao.id'], name='thong_bao_user_thong_bao_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['nhan_vien.id'], name='thong_bao_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='thong_bao_user_pkey')
    )
    # ### end Alembic commands ###
