"""update danhmuc_thu_tuc

Revision ID: f0edf813be54
Revises: 2bfd938400e2
Create Date: 2022-05-13 10:42:39.102628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0edf813be54'
down_revision = '2bfd938400e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('danhmuc_thu_tuc', sa.Column('trang_thai', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('danhmuc_thu_tuc', 'trang_thai')
    # ### end Alembic commands ###
