"""Update data table

Revision ID: f5b77884c468
Revises: 394759a95d9c
Create Date: 2022-07-05 14:56:20.967002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b77884c468'
down_revision = '394759a95d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nhan_vien', sa.Column('ho_ten', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nhan_vien', 'ho_ten')
    # ### end Alembic commands ###
