"""UPDATE TABLE LichSuChungChi active

Revision ID: f7a519030cdc
Revises: 79a04bec3feb
Create Date: 2022-06-09 10:30:49.255574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a519030cdc'
down_revision = '79a04bec3feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lich_su_chung_chi', sa.Column('trang_thai', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'lich_su_chung_chi', 'nhan_vien', ['lanh_dao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lich_su_chung_chi', type_='foreignkey')
    op.drop_column('lich_su_chung_chi', 'trang_thai')
    # ### end Alembic commands ###
