"""Update cosokinhdoanh

Revision ID: f82fb829a2ce
Revises: 7a9d689a95df
Create Date: 2022-05-27 10:35:45.690282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f82fb829a2ce'
down_revision = '7a9d689a95df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lk_loai_hinh_kinh_doanh',
    sa.Column('loai_hinh_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('co_so_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['co_so_kinh_doanh_id'], ['co_so_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['loai_hinh_kinh_doanh_id'], ['danhmuc_loai_hinh_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('loai_hinh_kinh_doanh_id', 'co_so_kinh_doanh_id')
    )
    op.create_table('lk_pham_vi_hoat_dong_kinh_doanh',
    sa.Column('pham_vi_hoat_dong_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('co_so_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['co_so_kinh_doanh_id'], ['co_so_kinh_doanh.id'], ),
    sa.ForeignKeyConstraint(['pham_vi_hoat_dong_kinh_doanh_id'], ['danhmuc_pham_vi_hoat_dong_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('pham_vi_hoat_dong_kinh_doanh_id', 'co_so_kinh_doanh_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_pham_vi_hoat_dong_kinh_doanh')
    op.drop_table('lk_loai_hinh_kinh_doanh')
    # ### end Alembic commands ###
