"""Update table duocsicoso

Revision ID: f9ac5273e970
Revises: 7e0a61a540e1
Create Date: 2022-05-30 11:15:23.333616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9ac5273e970'
down_revision = '7e0a61a540e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duoc_si_co_so',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chung_chi_hanh_nghe_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('co_so_kinh_doanh_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('vai_tro', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chung_chi_hanh_nghe_id'], ['chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['co_so_kinh_doanh_id'], ['co_so_kinh_doanh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('yeu_cau_chung_chi_hanh_nghe', 'ma_ho_so',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yeu_cau_chung_chi_hanh_nghe', 'ma_ho_so',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('duoc_si_co_so')
    # ### end Alembic commands ###
