"""create table danhmuc_loaihinh_kinh_doanh

Revision ID: fb96e6607bba
Revises: 70e3414bbbf1
Create Date: 2022-05-09 15:39:42.879594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb96e6607bba'
down_revision = '70e3414bbbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danhmuc_loai_hinh_kinh_doanh',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ma_loai_hinh', sa.String(), nullable=True),
    sa.Column('ten', sa.String(), nullable=True),
    sa.Column('ten_khong_dau', sa.String(), nullable=True),
    sa.Column('trang_thai', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tai_khoan',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tai_khoan', sa.String(), nullable=False),
    sa.Column('mat_khau', sa.String(), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tai_khoan')
    )
    op.create_table('vai_tro',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ten', sa.String(length=80), nullable=False),
    sa.Column('ten_en', sa.String(), nullable=True),
    sa.Column('vai_tro', sa.Unicode(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('nhan_vien',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('ho', sa.String(length=80), nullable=True),
    sa.Column('ten', sa.String(length=80), nullable=True),
    sa.Column('ten_khong_dau', sa.String(length=80), nullable=True),
    sa.Column('ngay_sinh', sa.TIMESTAMP(), nullable=True),
    sa.Column('gioi_tinh', sa.TIMESTAMP(), nullable=True),
    sa.Column('ma_cong_dan', sa.String(length=80), nullable=True),
    sa.Column('ngay_cap', sa.TIMESTAMP(), nullable=True),
    sa.Column('noi_cap', sa.String(length=80), nullable=True),
    sa.Column('dia_chi_thuong_tru', sa.String(), nullable=True),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('gioithieu', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('da_cap_chung_chi', sa.String(), nullable=True),
    sa.Column('dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nhan_vien')
    op.drop_table('vai_tro')
    op.drop_table('tai_khoan')
    op.drop_table('danhmuc_loai_hinh_kinh_doanh')
    # ### end Alembic commands ###
