"""update yeu cau chungchi_hanh_nghe

Revision ID: feae299f1027
Revises: f5061be6bd3a
Create Date: 2022-05-13 13:55:44.778771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'feae299f1027'
down_revision = 'f5061be6bd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yeu_cau_chung_chi_hanh_nghe',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nhan_vien_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ma_ho_so', sa.String(), nullable=False),
    sa.Column('loai_yeu_cau', sa.String(), nullable=True),
    sa.Column('so_giay_phep', sa.String(), nullable=True),
    sa.Column('co_quan_cap', sa.String(), nullable=True),
    sa.Column('van_bang_chuyen_mon_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ngay_hieu_luc', sa.TIMESTAMP(), nullable=True),
    sa.Column('ngay_het_han', sa.TIMESTAMP(), nullable=True),
    sa.Column('noi_cong_tac', sa.String(), nullable=True),
    sa.Column('loai_cap_chung_chi', sa.String(), nullable=True),
    sa.Column('hinh_thuc', sa.String(), nullable=True),
    sa.Column('lan_cap_thu', sa.String(), nullable=True),
    sa.Column('so_cchnd', sa.String(), nullable=True),
    sa.Column('thay_the_cchnd', sa.String(), nullable=True),
    sa.Column('yeu_cau_phien_dich', sa.Boolean(), nullable=True),
    sa.Column('so_quyet_dinh', sa.String(), nullable=True),
    sa.Column('ngay_quyet_dinh', sa.TIMESTAMP(), nullable=True),
    sa.Column('ly_do_mat_hong', sa.TEXT(), nullable=True),
    sa.Column('noi_dung_dieu_chinh', sa.TEXT(), nullable=True),
    sa.Column('noi_dung_tham_xet', sa.TEXT(), nullable=True),
    sa.Column('noi_dung_de_nghi', sa.TEXT(), nullable=True),
    sa.Column('noi_dung_yeu_cau_bo_sung_chuyen_vien', sa.TEXT(), nullable=True),
    sa.Column('noi_dung_yeu_cau_bo_sung_lanh_dao', sa.TEXT(), nullable=True),
    sa.Column('y_kien_lanh_dao', sa.JSON(), nullable=True),
    sa.Column('dinh_kem_chung_chi', sa.String(), nullable=True),
    sa.Column('dinh_kem_don_de_nghi', sa.String(), nullable=True),
    sa.Column('dinh_kem_anh_chan_dung', sa.String(), nullable=True),
    sa.Column('dinh_kem_van_bang_chuyen_mon', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_suc_khoe', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_thuc_hanh', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_dao_tao', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_cong_dan', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_ly_lich', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_cam_ket', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_le_phi', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_thay_doi', sa.String(), nullable=True),
    sa.Column('dinh_kem_xac_nhan_files', sa.String(), nullable=True),
    sa.Column('trang_thai_ho_so', sa.String(), nullable=True),
    sa.Column('ly_do_tu_choi_chuyen_vien', sa.String(), nullable=True),
    sa.Column('ly_do_tu_choi_lanh_dao', sa.String(), nullable=True),
    sa.Column('thoi_gian_thu_ly', sa.String(), nullable=True),
    sa.Column('ngay_het_han_ho_so', sa.String(), nullable=True),
    sa.Column('loai_ma_cchnd', sa.String(), nullable=True),
    sa.Column('thoi_gian_in_chung_chi', sa.TIMESTAMP(), nullable=True),
    sa.Column('thoi_gian_in_tham_xet', sa.TIMESTAMP(), nullable=True),
    sa.Column('thoi_gian_lanh_dao_duyet', sa.TIMESTAMP(), nullable=True),
    sa.Column('thoi_gian_nop_ho_so', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['van_bang_chuyen_mon_id'], ['danhmuc_van_bang_chuyen_mon.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_ho_so')
    )
    op.create_table('lk_danh_muc_hoi_dong_cchn',
    sa.Column('hoi_dong_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cchn_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['hoi_dong_id'], ['danhmuc_hoi_dong.id'], ),
    sa.PrimaryKeyConstraint('hoi_dong_id', 'cchn_id')
    )
    op.create_table('lk_nhan_vien_cchn',
    sa.Column('nhan_vien_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cchn_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('nhan_vien_id', 'cchn_id')
    )
    op.create_table('lk_nhan_vien_thu_ly_cchn',
    sa.Column('nhan_vien_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cchn_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('nhan_vien_id', 'cchn_id')
    )
    op.create_table('lk_pham_vi_hoat_dong_chuyen_mon_cchn',
    sa.Column('pham_vi_hoat_dong_chuyen_mon_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cchn_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['pham_vi_hoat_dong_chuyen_mon_id'], ['pham_vi_hoat_dong_chuyen_mon.id'], ),
    sa.PrimaryKeyConstraint('pham_vi_hoat_dong_chuyen_mon_id', 'cchn_id')
    )
    op.create_table('lk_thu_tuc_bo_sung_cchn',
    sa.Column('thu_tuc_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cchn_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['thu_tuc_id'], ['danhmuc_thu_tuc.id'], ),
    sa.PrimaryKeyConstraint('thu_tuc_id', 'cchn_id')
    )
    op.create_table('lk_thu_tuc_cchn',
    sa.Column('thu_tuc_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cchn_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['thu_tuc_id'], ['danhmuc_thu_tuc.id'], ),
    sa.PrimaryKeyConstraint('thu_tuc_id', 'cchn_id')
    )
    op.create_table('lk_vi_tri_hanh_nghe_cchn',
    sa.Column('vi_tri_hanh_nghe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cchn_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cchn_id'], ['yeu_cau_chung_chi_hanh_nghe.id'], ),
    sa.ForeignKeyConstraint(['vi_tri_hanh_nghe_id'], ['danhmuc_vi_tri_hanh_nghe.id'], ),
    sa.PrimaryKeyConstraint('vi_tri_hanh_nghe_id', 'cchn_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lk_vi_tri_hanh_nghe_cchn')
    op.drop_table('lk_thu_tuc_cchn')
    op.drop_table('lk_thu_tuc_bo_sung_cchn')
    op.drop_table('lk_pham_vi_hoat_dong_chuyen_mon_cchn')
    op.drop_table('lk_nhan_vien_thu_ly_cchn')
    op.drop_table('lk_nhan_vien_cchn')
    op.drop_table('lk_danh_muc_hoi_dong_cchn')
    op.drop_table('yeu_cau_chung_chi_hanh_nghe')
    # ### end Alembic commands ###
