"""update db

Revision ID: 70e3414bbbf1
Revises: da26021e6987
Create Date: 2022-05-05 09:39:15.908247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70e3414bbbf1'
down_revision = 'da26021e6987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khach_hang',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tai_khoan_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ho_ten', sa.String(), nullable=True),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=12), nullable=True),
    sa.Column('ma_bao_hiem', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tai_khoan', sa.Column('is_customer', sa.Boolean(), nullable=True))
    op.add_column('tai_khoan', sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tai_khoan', 'last_login_at')
    op.drop_column('tai_khoan', 'is_customer')
    op.drop_table('khach_hang')
    # ### end Alembic commands ###
